<!DOCTYPE html>
<html lang="de">
    <head>
    <title>Ansicht Kellner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="author" content="Stefan Pichel">
	<link rel="stylesheet" type="text/css" href="css/bestformat.css?v=2.9.12">
	
	<link rel="stylesheet" href="css/ospage.css?v=2.9.12" />
	<link rel="stylesheet" href="css/tablepanel.css?v=2.9.12" />
	<link rel="stylesheet" href="css/productpanel.css?v=2.9.12" />
	<link rel="stylesheet" href="css/grouppanel.css?v=2.9.12" />
	<link rel="stylesheet" href="css/groupitem.css?v=2.9.12" />
	<link rel="stylesheet" href="css/ordereditem.css?v=2.9.12" />
	<link rel="stylesheet" href="css/roompanel.css?v=2.9.12" />
	<link rel="stylesheet" href="css/extraspanel.css?v=2.9.12" />
	<link rel="stylesheet" href="css/actpanel.css?v=2.9.12" />
	<link rel="stylesheet" href="css/paypanel.css?v=2.9.12" />
	<link rel="stylesheet" href="css/numfield.css?v=2.9.12" />
  
    <link rel="stylesheet" href="php/3rdparty/jqueryui1-12-0/jquery-ui.min.css" />
    <script src="php/3rdparty/jquery-2.2.4.min.js"></script>
    <script src="php/3rdparty/jqueryui1-12-0/jquery-ui.min.js"></script>
   <script src="elements/tablemap.js?v=2.9.12"></script>
   <script src="elements/grouping.js?v=2.9.12"></script>
   <script src="elements/extra.js?v=2.9.12"></script>
   <script src="elements/waiterutils.js?v=2.9.12"></script>
   <script src="elements/phases.js?v=2.9.12"></script>
   <script src="utilities.js?v=2.9.12"></script>
   <script src="receiptutils.js?v=2.9.12"></script>
   
   <script>
function sendNewOrders(a,b,c){var e=getTableid();0!=neworders.length?(a={tableid:e,prods:neworders,print:a?1:0,payprinttype:"s",orderoption:$("#orderoption").val()},a=waiter_addDeliveryData(a),0===performanceMeasureTimer&&(perfStartTime=(new Date).getTime()),doAjaxTransmitData("POST","php/contenthandler.php?module=queue&command=addProductListToQueue",a,handleSentNewOrders,"Fehler bei Produktversand",{doGotoPaydesk:b,doUpdateChangeTableBtnIfTableIsSelected:c})):alert("Es sind keine Produkte ausgew\u00e4hlt worden.")}
function checkEndPerformanceMeaurement(){if(0===performanceMeasureTimer){performanceMeasureTimer=PERFTIMER;var a={task:"waitersendorder",elapsedtime:(new Date).getTime()-perfStartTime};doAjax("GET","php/contenthandler.php?module=admin&command=addperformancedata",a,null,null,!0)}else performanceMeasureTimer--}
function handleSentNewOrders(a,b){checkEndPerformanceMeaurement();"OK"!==a.status?(void 0!==a.msg?alert("Es ist ein Fehler beim Versenden der Bestellung aufgetreten: "+a.msg):alert("Es ist ein Fehler beim Versenden der Bestellung aufgetreten"),0<neworders.length&&(allowPrintAndOrderBtn=!0)):(clearNewOrderPrice(),clearLiveOrders(),neworders=[],$("#search").val(""),waiter_clearDeliveryFields(),refreshGui(),b.doUpdateChangeTableBtnIfTableIsSelected&&updateChangeTableBtnIfTableIsSelected(),b.doGotoPaydesk&&
goPayDesk())}function refreshGui(){requestRoomInformation();clearProductsSelection();requestProdInformation();requestOrderedInformation();displayPanels();allowPrintAndOrderBtn=!0}function getTableid(){if(null!==selectedroomindex)return 0>selectedroomindex?0:null!==selectedtableindex?roominfo.roomstables[selectedroomindex].tables[selectedtableindex].id:0}
function moveItems(){$("#selectiondialog").dialog({autoOpen:!1,modal:!0,height:400,buttons:{Abbrechen:function(){$(this).dialog("close")}}});var a=getRoomsForDialog();$("#selectiondialog").html(a);$("#selectiondialog").dialog("open");$(".ui-dialog-buttonset .ui-button").css("background-color","#44ff44");$(".ui-widget-header").css("background-color","#ff4400");bindMoveItemsRoom()}
function bindMoveItemsRoom(){$(".roomchangeitem").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=parseInt(this.id.split("_")[1]);var b=getTablesForDialog(a);$("#selectiondialog").dialog("open");$("#selectiondialog").html(b);bindMoveItemsTable(a)})}
function bindRightButtons(){$("#sendNewOrders").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();allowPrintAndOrderBtn&&(allowPrintAndOrderBtn=!1,unZoomTableMap(),sendNewOrders(!1,!1,!0))});$("#paydeskbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();allowPrintAndOrderBtn&&(allowPrintAndOrderBtn=!1,unZoomTableMap(),0<neworders.length?1==waitergopayprint?sendNewOrders(!0,!0,!1):sendNewOrders(!1,!0,!1):goPayDesk())});$("#workbtn").off("click").on("click",
function(a){allowPrintAndOrderBtn&&(allowPrintAndOrderBtn=!1,unZoomTableMap(),0<neworders.length&&sendNewOrders(!0,!1,!1,!0))});$("#goorderbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();unZoomTableMap();goOrderDesk()});$("#mainmenudlg").dialog({autoOpen:!1,modal:!0});$("#changetablebtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();unZoomTableMap();moveItems()});$("#tablerecordsbtn").off("click").on("click",function(a){a.stopImmediatePropagation();
a.preventDefault();a=getTableid();doAjax("GET","php/contenthandler.php?module=queue&command=getRecords&tableid="+a,null,showRecords,!0)})}function showRecords(a){"OK"!==a.status?alert("Fehler aufgetreten: "+a.msg):(a=createTableRecords(a),$("#recordsdlg").dialog({autoOpen:!1,modal:!0,height:570,width:600,buttons:{Abbrechen:function(){$(this).dialog("close")}}}),$("#recordsdlg").dialog("open"),$("#recordsdlg").html(a))}
function createTableRecords(a){var b=[["Bestellung","Ordering","Ordenar"],["Rechnung","Bill","Pagar"],["Artikelstorno","Discard product","Descartar producto"],["Rechnungsstorno","Discard bill","Descartar pago"],["Rechnungs- und Artikelstorno","Discard bill and product","Descrtar pago y producto"],["Tischwechsel Produktentfernung","Move products to other table","Productos a otra mesa"],["Tischwechsel Produktbuchung","Received moved products","Recibo productos de otra mesa"],["Lieferbon","Delivery receipt",
"Recibo de entrega"],["Storno Lieferbon","Discard delivery receipt","Descartar recibo de entrega"],["Storno Lieferbon und Artikel","Discard delivery receipt and products","Descartar recibo de entrega y productos"]];a=a.msg;var c="<h2>Tischprotokoll</h2>";if(0===a.length)return c+="keine Eintr\u00e4ge";c+="<ul>";a.forEach(function(e,f){f=toHtml(e.time);var g=toHtml(e.username),h=toHtml(e.action);c+="<li>"+f+" "+g+" - <b>"+b[h][0]+"</b>:<br>";e=e.prods;c+="<ul>";e.forEach(function(k,m){m=toHtml(k.name);
var l=toHtml(k.comment);k=toHtml(k.extras);c+="<li>"+m;""!==l&&(c+=" ["+l+"]");""!=k&&(c+=" ("+k+")")});c+="</ul>"});return c+="</ul>"}
function bindMoveItemsTable(a){$(".tablechangeitem").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();moveToRoomIndex=a;b=parseInt(this.id.split("_")[1]);b=roominfo.roomstables[a].tables[b];moveToTableId=b.id;"-1"!=selectedroomindex?(b=roominfo.roomstables[selectedroomindex].tables[selectedtableindex],moveFromTableId=b.id,$("#selectiondialog").dialog("close"),doAjax("GET","php/contenthandler.php?module=queue&command=getProdsForTableChange",{tableId:moveFromTableId},
insertProductsToChangeTableDlg,null,!0)):$("#selectiondialog").dialog("close")})}
function insertProductsToChangeTableDlg(a){"OK"!=a.status?alert("Abfrageproblem bei Query nach Artikeln eines Tisches"):(prodsToMove=a.msg,allselected=1,updateProdToMoveList(),$("#selectallnothing").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();allselected=1-allselected;for(b=0;b<prodsToMove.length;b++)prodsToMove[b]["class"]=1===allselected?"selecteditem":"unselecteditem";updateProdToMoveList()}))}
function updateProdToMoveList(){1===allselected?$("#selectallnothing_txt").val(W_UNSELALL[lang]):$("#selectallnothing_txt").val(W_SELALL[lang]);for(var a="",b=0;b<prodsToMove.length;b++){var c=prodsToMove[b],e="prodToMove_"+b,f=" (unbezahlt)",g=c.kind,h="proditemselected";void 0===c["class"]&&(c["class"]="selecteditem");var k=c["class"];"unselecteditem"===k&&(h="proditemunselected");"unpaid_undelivered"===c.status&&(f=" (unbezahlt, nicht serviert)");var m=workflowconfigfood;1==g&&(m=workflowconfigdrinks);
if(m==WORKFLOW_WORK||m==WORKFLOW_WORK_TRANSFER)f="";a+="<li class='prodToMoveEl "+h+"' id='"+e+"' ><span class='"+(k+"'>"+c.productname+f+"</span></li>")}$("#productsToMoveList").html(a);$("#moveItemdslg").dialog({autoOpen:!1,modal:!0,height:600,width:800,buttons:{Abbrechen:function(){$(this).dialog("close")},Verschieben:function(){$(this).dialog("close");doMoveItems()}}});$("#moveItemdslg").dialog("open");handleClickOnMoveableProd()}
function handleClickOnMoveableProd(){$(".prodToMoveEl").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id.split("_")[1];a=prodsToMove[a];a["class"]="unselecteditem"==a["class"]?"selecteditem":"unselecteditem";updateProdToMoveList()})}
function doMoveItems(){$("#moveItemdslg").dialog("close");for(var a=[],b=0;b<prodsToMove.length;b++){var c=prodsToMove[b];"selecteditem"==c["class"]&&(a[a.length]=c.queueid)}0===a.length?alert(W_NO_PRODS_SELECTED[lang]):(a=a.join(),doAjax("POST","php/contenthandler.php?module=queue&command=changeTable",{fromTableId:moveFromTableId,toTableId:moveToTableId,queueids:a},resultOfChangeTable,"Fehler Tischwechsel",!0))}
function resultOfChangeTable(a){"OK"!=a.status?alert("Fehler "+a.code+": "+a.msg+"\n\nM\u00f6glicherweise hat ein Kollege\nin der Zwischenzeit Produkte zugestellt."):alert("Tischwechsel durchgef\u00fchrt!");refreshGui()}function requestRoomInformation(){1==restaurantmode&&(perfStartTimeShowAllRooms=(new Date).getTime(),doAjax("GET","php/contenthandler.php?module=roomtables&command=showAllRooms",null,insertRoomInfo,null,!0))}
function checkEndPerformanceMeaurementShowAllRooms(){var a={task:"waitershowallrooms",elapsedtime:(new Date).getTime()-perfStartTimeShowAllRooms};doAjax("GET","php/contenthandler.php?module=admin&command=addperformancedata",a,null,null,!0)}function insertRoomInfo(a){checkEndPerformanceMeaurementShowAllRooms();roominfo=a;showRooms()}function getTableMapPreferences(){doAjax("GET","php/tablemap.php?command=getTableMapPreferences",null,insertTMInfo,"Keine TM-Information",!0)}
function showRooms(){var a=roominfo.roomstables,b="osroom-desk-0",c="osroom-desk-sel-0";1==osroombtnsize?(b="osroom-desk-1",c="osroom-desk-sel-1"):2==osroombtnsize&&(b="osroom-desk-2",c="osroom-desk-sel-2");var e="";$.each(a,function(f,g){e=selectedroomindex===f?e+('<div id="room_'+f+'" class="roomitemselected '+c+'">'+g.name+"</div>"):e+('<div id="room_'+f+'" class="roomitem '+b+'">'+g.name+"</div>")});a=roominfo.takeawayprice.pricesum.replace(".",decpoint)+" "+currency;if(0<roominfo.takeawayprice.prodcount||
""!=a)a='<div class="roomtogoaccounted">'+a+"</div>";1==showtogo?(0>selectedroomindex&&"waiter"===panelMode?(0==selectedtableindex?$("#deliverydetails").hide():$("#deliverydetails").show(),e+='<div id="room_-1" class="roomitemselected roomtogo '+c+'">'):($("#deliverydetails").hide(),e+='<div id="room_-1" class="roomitem roomtogo '+b+'">'),e+='<div class="roomname">Zum Mitnehmen</div>',e+=a,e+="</div>"):$("#deliverydetails").hide();$("#roompanel").html(e);$("#tablepanelcontent").html("");showRoomTableTextInfo();
showTablesForRoomIndex();bindingRoom();1==showtogo&&bindDeliveryPanel()}
function bindDeliveryPanel(){$("#deliverydetailsbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();$("#deliveryfields").show();$("#ordersendemaildiv").show()});$("#ordersendemaildiv").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();1==ordersendemail?($("#ordersendemailyes").hide(),$("#ordersendemailno").show()):($("#ordersendemailyes").show(),$("#ordersendemailno").hide());ordersendemail=1-ordersendemail})}
function getRoomsForDialog(){var a="";$.each(roominfo.roomstables,function(b,c){a+='<div id="changeroom_'+b+'" class="roomchangeitem">'+c.name+"</div>"});return a}
function bindingRoom(){$(".roomitem").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();var b=parseInt(this.id.split("_")[1]);$("#changetablebtn").hide();$("#tablerecordsbtn").hide();"waiter"==panelMode?0<neworders.length?($("#unsentorderdlg").dialog({autoOpen:!1,modal:!0,height:400,buttons:{Nein:function(){$(this).dialog("close")},Ja:function(){$(this).dialog("close");discardChangeRoom(b)}}}),$("#unsentorderdlg").dialog("open")):(changeRoom(b),"-1"==selectedroomindex&&
($("#tablerecordsbtn").show(),startProductDisplay())):(changeRoom(b),goPayDesk())})}function clearSearchResult(){$("#search").val("");productFilter=null;$("#barcode").val("");showAllProdsToChoose()}function discardChangeRoom(a){clearSearchResult();neworders=[];groupedNewOrders=null;showNewOrders();changeRoom(a)}function clearCurrentPhaseAndInitialize(){phases.clearCurrentPhase();1==showphases&&phases.setCurrentPhase(defaultphase,!0);phases.showPhaseInDesktop()}
function changeRoom(a){clearSearchResult();$("#orderoption").val("");clearProductsSelection();clearCurrentPhaseAndInitialize();selectedtableindex=null;selectedroomindex=a;1==restaurantmode&&showRooms();requestOrderedInformation()}
function showRoomTableTextInfo(){var a="Keine Auswahl";null!==selectedroomindex&&(0>selectedroomindex?a="Zum Mitnehmen":(a="Raum: "+roominfo.roomstables[selectedroomindex].name,null!==selectedtableindex&&(a+=" - Tisch: "+roominfo.roomstables[selectedroomindex].tables[selectedtableindex].name)));$("#location").html(a)}
function showTablesForRoomIndex(){if(0<=selectedroomindex&&null!==selectedroomindex){var a=roominfo.roomstables[selectedroomindex].id,b=shallDisplayRoom(a);if(1==b.show){$("#tablepanelcontent").hide();d=new Date;$("#mapimgpart").attr("src","php/tablemap.php?command=getTableMapImgAsPng&showBubbles=0&roomid="+a+"&"+d.getTime());$("#tablemapcontent").show();var c=new Tablemap(selectedroomindex,null,""),e=roominfo.roomstables[selectedroomindex].tables,f=null;null!=selectedtableindex&&(f=roominfo.roomstables[selectedroomindex].tables[selectedtableindex].id);
b=c.createOverlay("#mapimgpart",b.pos,W_TO_PAY[lang],decpoint,currency,e,ostablebtnsize,f);$("#tableoverlay").html(b);c.bindingForOverlaySelection(handleClickInTablemap.bind(this),a,e,switchZoomView)}else showTablesListForRoomIndex();bindTableMapClick()}else showTablesListForRoomIndex()}
function switchZoomView(){tableMapIsZoomed?($(".main").show(),$("#roompanel").show(),tableMapIsZoomed=!1,$("#mapimgpart").removeClass("zoomed"),$("#mapimgpart").addClass("notzoomed")):(tableMapIsZoomed=!0,$("#mapimgpart").addClass("zoomed"),$("#mapimgpart").removeClass("notzoomed"))}function unZoomTableMap(){tableMapIsZoomed=!0;switchZoomView()}
function handleClickInTablemap(a){selectedtableindex=null;for(var b=roominfo.roomstables[selectedroomindex].tables,c=0;c<b.length;c++)if(b[c].id==a.tableid){selectedtableindex=c;break}unZoomTableMap();unfocusTableMap();changeTable(selectedtableindex);$("#tablerecordsbtn").show();"waiter"===panelMode?($("#changetablebtn").show(),startProductDisplay()):($("#changetablebtn").hide(),goPayDesk())}
function showTablesListForRoomIndex(){$("#tablemapcontent").hide();var a="ostable-desk-0";1==ostablebtnsize?a="ostable-desk-1":2==ostablebtnsize&&(a="ostable-desk-2");if(0<=selectedroomindex&&null!==selectedroomindex){var b=roominfo.roomstables[selectedroomindex].tables,c="";$.each(b,function(e,f){c=null!=selectedtableindex&&b[selectedtableindex].id==f.id?c+('<div id="table_'+e+'" class="tableelement tableitemselected '+a+'">'):c+('<div id="table_'+e+'" class="tableelement tableitem '+a+'">');e=f.name;
var g=f.reservations;""!=g&&(g=g.split(",").join("<br>"),e+="<br><span class='tablereservations'>("+g+")</span>");c+='  <header class="tablename">'+e+"</header>";e=f.pricesum;if(0<f.unpaidprodcount||0!=e)f=e.replace(".",decpoint)+" "+currency,c+='<div class="tableopen">'+f+"</div>";c+="</div>"});$("#tablepanelcontent").html(c)}else $("#tablepanelcontent").html("");$("#tablepanelcontent").show();bindingTable()}
function getTablesForDialog(a){var b="";$.each(roominfo.roomstables[a].tables,function(c,e){b+='<div id="changetable_'+c+'" class="tablechangeitem">'+e.name+"</div>"});return b}function updateChangeTableBtnIfTableIsSelected(){$("#tablerecordsbtn").show();"waiter"==panelMode?$("#changetablebtn").show():$("#changetablebtn").hide()}
function bindingTable(){$(".tableitem").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();var b=parseInt(this.id.split("_")[1]);"waiter"===panelMode?($("#tablerecordsbtn").show(),$("#changetablebtn").show(),0<neworders.length?($("#unsentorderdlg").dialog({autoOpen:!1,modal:!0,height:400,buttons:{Nein:function(){$(this).dialog("close")},Ja:function(){$(this).dialog("close");discardChangeTable(b)}}}),$("#unsentorderdlg").dialog("open")):(changeTable(b),startProductDisplay())):
(changeTable(b),goPayDesk())})}function discardChangeTable(a){neworders=[];groupedNewOrders=null;clearCurrentPhaseAndInitialize();showNewOrders();changeTable(a)}function changeTable(a){clearSearchResult();$("#orderoption").val("");clearCurrentPhaseAndInitialize();selectedtableindex=a;showRoomTableTextInfo();showTablesForRoomIndex();requestOrderedInformation();cheaptestAlreadySubtracted=!1}
function startProductDisplay(){selectedprodid=selectedtypeid=null;clearProductsSelection();requestProdInformation();requestOrderedInformation();clearSearchResult();$("#searchpanel").show();1==usebarcode&&document.getElementById("barcode").focus();$("#remarkpanel").show()}
function clearProductsSelection(){neworders=[];groupedNewOrders=[];selectedtypeid=null;$("#groupchain").html("");$("#groupchoice").html("");$("#productspanel").html("");$("#remark").val("");$("#orderoption").val("");$("#neworders").html("");$("#ordered").html("");$("#searchpanel").hide();$("#remarkpanel").hide()}
function bindTableMapClick(){$("#tablemapcontent").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();if(0===tableMapInFocus){tableMapWidth=document.getElementById("mapimgpart").width;tableMapHeight=document.getElementById("mapimgpart").height;a=document.body.clientWidth;var b=$(window).height(),c=document.getElementById("roompanel").clientHeight;b-=c;document.getElementById("mapimgpart").style.zIndex="100";document.getElementById("mapimgpart").style.width=a+"px";
document.getElementById("mapimgpart").style.height=b+"px";$("#roompanel").hide();tableMapInFocus=1}else unfocusTableMap()})}function unfocusTableMap(){1===tableMapInFocus&&(document.getElementById("mapimgpart").style.width=tableMapWidth+"px",document.getElementById("mapimgpart").style.height=tableMapHeight+"px",document.getElementById("mapimgpart").style.zIndex="auto",$("#roompanel").show(),tableMapInFocus=0)}var allOrderdItems=[];
function requestOrderedInformation(){if("waiter"===panelMode){var a=0;if(null!=selectedroomindex||null!=selectedtableindex){var b=!1;null!=selectedroomindex&&0>selectedroomindex&&(b=!0);if(null!=selectedroomindex&&"-1"!=selectedroomindex&&null!=selectedroomindex){var c=roominfo.roomstables[selectedroomindex].tables[selectedtableindex];void 0!==c&&(a=c.id,b=!0)}b&&doAjax("GET","php/contenthandler.php?module=queue&command=getJsonLongNamesOfProdsForTableNotDelivered&tableid="+a,null,insertOrderedInformation,
!0)}}}function insertOrderedInformation(a){allOrderdItems=a;a=new Grouping(a,createTxtAssignedProd);a.group();a=""+a.outputList(createListElOfAssignedProd);$("#ordered").html(a);bindOrderedItem()}
function createTxtAssignedProd(a,b){void 0==b&&(b="");var c="";""!=a.option&&(c="<p><i>"+toHtml(a.option)+"</i>");var e="",f=toHtml(a.longname);1==a.togo&&(e="To-Go: ");f='<div class="ordereditem-name '+b+'">'+e+'<span class="ordereditem-bold '+b+'">'+f+"</span></div>";1==a.pricechanged&&(f+=" &#9758; <span class='priceatarticle'>"+a.price.replace(".",decpoint)+" "+currency+"</span>");isUnitOfAmountTypeNotPieceNotVoucher(a.unit)&&(b=g_units_arr[a.unit].text,e=a.unitamount.replace(".",decpoint),f+=
" ("+e+" "+b+")");0<a.phase&&(b=phases.getPhaseName(a.phase),f+=b);b="";"1"==a.isready&&(b+=" &#9758");"1"==a.isCooking&&(b+=" &#9832");"1"==a.isPaid&&(b+=" &#9745");return f+'<div class="oredereditem-misc">'+c+b+createExtraParagraphForOrderedEl(a.extras,a.extrasamounts)+"</div>"}
function createListElOfAssignedProd(a){var b="";1==priceassigneddesktop&&(b="<p style='margin-bottom: 3mm;'/>"+createPriceOfAssignedArticle(a,decpoint,currency));var c="";"count"in a&&1<a.count&&(c=0==preferimgdesk?'<div class="ordereditem-count">'+a.count+"x </div>":'<div class="ordereditem-count whitebackground">'+a.count+"x </div>");var e="";if(0==preferimgdesk)e+="<div id='ordered_"+a.id+"' class='ordereditem-item-sent' >"+c+createTxtAssignedProd(a)+b+"</div>";else{var f="php/contenthandler.php?module=products&command=getprodimage&prodid="+
a.prodid+"&size=m";b="<span>"+c+createTxtAssignedProd(a,"whitebackground")+b+"</span>";e+='<div id="ordered_'+a.id+'" class="ordereditem-item-sent" '+createImageStyle(f)+" >"+b+"</div>"}return e}function createExtraParagraphForOrderedEl(a,b){if(null==a||""==a)return"";for(var c=[],e=0;e<a.length;e++)c[c.length]=b[e]+"x "+toHtml(a[e]);return"<p>"+c.join("<br>")}
function bindOrderedItem(){$(".ordereditem-item-sent").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id.split("_")[1];for(var b=0;b<allOrderdItems.length;b++){var c=allOrderdItems[b];if(a==c.id){handleClickOnOrderedItem(c,a);break}}})}
function handleClickOnOrderedItem(a,b){b=a.isready;var c=a.isPaid,e=a.isCooking;a.isminusarticle==IS_MINUS_ARTICLE?$("#ordereditemreorder").hide():$("#ordereditemreorder").show();var f="Das Produkt ist diesem Tisch zugewiesen.";"1"==c&&"1"==b?f="Produkt wurde schon zubereitet und bezahlt.":"1"==b?f="Produkt wurde schon zubereitet.":"1"==c?f="Produkt wurde schon bezahlt.":"1"==e&&(f="Produkt wird soeben zubereitet.");$("#ordereditem-info").html(f);$("#ordereditemdlg").dialog({autoOpen:!1,modal:!0,
height:400,width:600,position:{my:"center top",at:"center top",of:"body"}});""!=cancelunpaidcode?($("#orderedcancelpanel").show(),$("#cancelcode").val("")):$("#orderedcancelpanel").hide();$("#ordereditemdlg").dialog("open");bindOrderItemAction(a)}
function bindOrderItemAction(a){var b=a.isready,c=a.isPaid,e=a.isCooking,f=a.id;$("#ordereditemcancel").off("click").on("click",function(g){g.stopImmediatePropagation();g.preventDefault();$("#ordereditemdlg").dialog("close")});$("#ordereditemremove").off("click").on("click",function(g){g.stopImmediatePropagation();g.preventDefault();if(""!=cancelunpaidcode&&(g=$("#cancelcode").val(),cancelunpaidcode!=g)){alert("Falscher Stornocode!");return}removeProductFromQueue(f,c,e,b,!0);$("#cancelcode").val("")});
$("#deleteallordereditems").off("click").on("click",function(g){g.stopImmediatePropagation();g.preventDefault();if(""!=cancelunpaidcode&&(g=$("#cancelcode").val(),cancelunpaidcode!=g)){alert("Falscher Stornocode!");return}removeAllAssignedProds();$("#cancelcode").val("")});$("#ordereditemreorder").off("click").on("click",function(g){g.stopImmediatePropagation();g.preventDefault();reorderProduct(a.prodid,a.extrasids,a.extras,a.extrasamounts)})}
function removeAllAssignedProds(){for(var a=0;a<allOrderdItems.length;a++)removeProductFromQueue(allOrderdItems[a].id,allOrderdItems[a].isPaid,allOrderdItems[a].isCooking,allOrderdItems[a].isready,!1);requestOrderedInformation();$("#ordereditemdlg").dialog("close")}
function removeProductFromQueue(a,b,c,e,f){$.ajax({type:"POST",dataType:"json",url:"php/contenthandler.php?module=queue&command=removeProductFromQueue",data:{queueid:a,isPaid:b,isCooking:c,isReady:e},async:!1,success:function(g){f&&(requestOrderedInformation(),$("#ordereditemdlg").dialog("close"))},error:function(g){alert("Sorry, Fehler bei Produktentfernung!")}})}
function reorderProduct(a,b,c,e){var f=getProdProperties(a);if(0!=f.unit)alert(W_NO_REORDER_VAR_PRICE[lang]);else{for(var g=[],h=0;h<b.length;h++)g[g.length]={id:b[h],name:c[h],amount:e[h]};$("#ordereditemdlg").dialog("close");b=calcTotalPriceOfProdAndExtras(f.price,g);addProductToNewOrders(a,"",g,"NO",0,b,f.unit,f.phase)}}function requestProdInformation(){doAjax("GET","php/contenthandler.php?module=products&command=getAllTypesAndAvailProds",null,insertProductInformation,!0)}
function insertProductInformation(a){productInformation=a;allextras={};for(var b=0;b<a.extras.length;b++){var c=a.extras[b];allextras[c.id]=c.price}updateProductInfoDisplay()}function updateProductInfoDisplay(){"waiter"===panelMode&&(showAllTypesToChoose(),showAllProdsToChoose(),$("#searchpanel").show(),1==usebarcode&&document.getElementById("barcode").focus(),$("#remarkpanel").show(),allowPrintAndOrderBtn=!0)}
function getType(a){for(var b=productInformation.types,c=0;c<b.length;c++){var e=b[c];if(e.id==a)return e}return null}function getSubTypes(){var a=productInformation.types,b=[];if(null!==selectedtypeid)for(var c=getType(selectedtypeid),e=0;e<a.length;e++){var f=a[e];null!==f&&f.ref==c.id&&(b[b.length]={id:f.id,name:f.name})}else for(e=0;e<a.length;e++)if(f=a[e],null==f.ref||0==f.ref)b[b.length]={id:f.id,name:f.name};return b}
function getAllProds(a){var b=productInformation.prods,c=[];if(null!==a){a=a.trim().toLowerCase();for(var e=0;e<b.length;e++){var f=b[e];0<=f.longname.toLowerCase().indexOf(a)&&(c[c.length]={id:f.id,name:f.name,amount:f.amount,price:f.price})}}else if(null!==selectedtypeid)for(a=getType(selectedtypeid),e=0;e<b.length;e++)f=b[e],f.ref==a.id&&(c[c.length]={id:f.id,name:f.name,amount:f.amount,price:f.price});else for(e=0;e<b.length;e++)if(f=b[e],null===f.ref||0==f.ref)c[c.length]={id:f.id,name:f.name,
amount:f.amount,price:f.price};return c}function showAllTypesToChoose(){var a="";if("-1"==selectedroomindex||null!=selectedtableindex){var b=getSubTypes();$.each(b,function(c,e){a=selectedtypeid==e.id?a+('<div id="type_'+e.id+'" class="groupitemchoiceselected">'+e.name+"</div>"):a+('<div id="type_'+e.id+'" class="groupitemchoice">'+e.name+"</div>")})}$("#groupchoice").html(a);showChain();bindType()}
function bindType(){$(".groupitemchoice").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();$("#search").val("");productFilter=null;showAllProdsToChoose();selectedtypeid=parseInt(this.id.split("_")[1]);updateProductInfoDisplay()})}
function showAllProdsToChoose(){var a="osprod-desk-0";1==osprodbtnsize?a="osprod-desk-1":2==osprodbtnsize&&(a="osprod-desk-2");var b="";if("-1"==selectedroomindex||null!=selectedtableindex){var c=getAllProds(productFilter);$.each(c,function(e,f){e="<br><span class='priceatarticle'>"+f.price.replace(".",decpoint)+"</span>";if(0==preferimgdesk)b+='<div id="prod_'+f.id+'" class="productitem '+a+'">'+f.name+e;else{var g="<span class='whitebackground'>"+f.name+"</span>";b+='<div id="prod_'+f.id+'" class="productitem '+
a+'" '+createImageStyle("php/contenthandler.php?module=products&command=getprodimage&prodid="+f.id+"&size=m")+" >"+g+e}"null"!=f.amount&&11>f.amount&&(b+="<br><span class='warning whitebackground'>("+W_ONLY[lang]+" "+f.amount+")</span>");b+="</div>"})}$("#productspanel").html(b);bindProduct();bindRemark();bindOrderOption()}
function findProdWithBarcode(a){if("-1"==selectedroomindex||null!=selectedtableindex)for(var b=productInformation.prods,c=0;c<b.length;c++){var e=b[c],f=e.barcode;f=f.split("-").join("");f=f.split(" ").join("");if(f==a)return e}return null}function createImageStyle(a){return" style=\"background-image: url('"+a+"'); background-size: cover; background-repeat: no-repeat;  background-position: center center; \" "}
function getTypeChain(){var a=getType(selectedtypeid);if(null==a)return[];for(var b=[a];a=a.ref,null!=a&&0!=a;)a=getType(a),b[b.length]=a;return b}function showChain(){var a="";if("-1"==selectedroomindex||null!=selectedtableindex){var b=getTypeChain();a+='<div id="groupchainitem_-1" class="groupitem">Auswahl</div>';for(var c=b.length-1;0<=c;c--){var e=b[c];a+='<div id="groupchainitem_'+e.id+'" class="groupitem">'+e.name+"</div>"}}$("#groupchain").html(a);bindChain();bindSearch()}
function bindChain(){$(".groupitem").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();selectedtypeid=parseInt(this.id.split("_")[1]);"-1"==selectedtypeid&&(selectedtypeid=null);updateProductInfoDisplay();$("#search").val("");productFilter=null;showAllProdsToChoose()})}
function bindSearch(){$("#search").off("keyup").on("keyup",function(a){a.stopImmediatePropagation();a.preventDefault();productFilter=$("#search").val().trim().toLowerCase().trim();""==productFilter&&(productFilter=null);showAllProdsToChoose()});if(1==usebarcode)$("#barcode").off("keyup").on("keyup",function(a){a.stopImmediatePropagation();a.preventDefault();handleBarcodeInput(a,!1)})}
function bindProduct(){$(".productitem").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=parseInt(this.id.split("_")[1]);handleClickOnProd(a)})}
function handleClickOnProd(a){var b=getProdEntry(a);if(canProdBeOrdered(b)){$("#search").val("");$("#barcode").val("");1==usebarcode&&$("#barcode").focus();selectedprodid=a;var c=$("#remark").val(),e=b.extras,f=b.unit,g=phases.getCurrentPhase();null!=e&&0<e.length||1==f?(1==b.unit?(requestPriceInExtras=!0,presetPriceInExtras=""):requestPriceInExtras=!1,showExtras(b,c)):($("#enterpricedlg").data("prodid",a),$("#enterpricedlg").data("option",c),$("#enterpricedlg").data("unit",b.unit),$("#enterpricefield").val(""),
$("#entervoucherid").val(""),isUnitOfAmountTypeNotPieceNotVoucher(b.unit)?(enterpricedlgshown=!0,a="Preiseingabe",1<b.unit&&(a="Eingabe "+g_units_arr[b.unit].longtext),$("#entervalueunit").html(a),$("#enterpricedlg").dialog({autoOpen:!1,modal:!0,height:570,width:400,buttons:{Abbrechen:function(){$(this).dialog("close")}}}),$("#enterpricedlg").dialog("open"),$("#dlgvoucherarea").hide(),$("#dlgpricearea").show(),bindEnterPriceOrVoucherNumbers()):8==b.unit?addProductToNewOrders(a,c,null,"NO",0,null,
9,1,0):9==b.unit?($("#entervalueunit").html("Gutschein einl\u00f6sen"),$("#enterpricedlg").dialog({autoOpen:!1,modal:!0,height:570,width:400,buttons:{Abbrechen:function(){$(this).dialog("close")}}}),$("#enterpricedlg").dialog("open"),$("#dlgvoucherarea").show(),$("#dlgpricearea").hide(),bindEnterPriceOrVoucherNumbers()):addProductToNewOrders(a,c,null,"NO",0,null,0,1,g))}}
function bindEnterPriceOrVoucherNumbers(){$(".numfield td").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=$(this).html();var b=$(this).attr("class");"keyboardapply"===b?applyPriceEnter():"applyvoucherid"===b?applyVoucherId():(b=String($("#enterpricefield").val()),$("#enterpricefield").val(b+a))})}
function applyVoucherId(){var a=$("#enterpricedlg").data("prodid"),b=$("#entervoucherid").val().trim();""===b?alert("Keine Gutscheinnummer angegeben."):($("#enterpricedlg").dialog("close"),addProductToNewOrders(a,b,null,0,0,0,9,1,null))}
function applyPriceEnter(){var a=$("#enterpricedlg").data("prodid"),b=$("#enterpricefield").val(),c=$("#enterpricedlg").data("option"),e=$("#enterpricedlg").data("unit");b=b.trim();b=b.replace(decpoint,".");""!==b&&$.isNumeric(b)?($("#enterpricedlg").dialog("close"),1==e?addProductToNewOrders(a,c,null,b,0,b,0,1,null):addProductToNewOrders(a,c,null,"NO",0,null,e,b,null)):alert(W_NO_VALID_PRICE[lang])}function bindRemark(){bindRemarkCore("#remark","commentitem","applyComment")}
function bindOrderOption(){bindRemarkCore("#orderoption","ordercommentitem","applyOrderComment")}
function bindRemarkCore(a,b,c){$(a).off("click").on("click",function(e){if(null!==genComments&&0<genComments.length){e.stopImmediatePropagation();e.preventDefault();e="";for(var f=0;f<genComments.length;f++)e+="<li class='"+b+"'>"+toHtml(genComments[f].comment)+"</li>";$("#commentschoice").html(e);$("#gencommentsdlg").dialog({autoOpen:!1,modal:!0,height:600,buttons:{Abbrechen:function(){$(this).dialog("close")},Anwenden:function(){$(this).dialog("close");window[c]()}}});$("#gencommentsdlg").dialog("open");
$("#gencommentsdlg").css("height",52*genComments.length+150);$("#generalcommentfield").val("");$(".ui-dialog-buttonset .ui-button:nth-child(1)").css("background-color","#eeeeee");$(".ui-dialog-buttonset .ui-button:nth-child(1)").css("color","#ff0000");$(".ui-dialog-buttonset .ui-button:nth-child(2)").css("background-color","#00ff00");$(".ui-dialog-buttonset .ui-button:nth-child(2)").css("color","#000000");$(".ui-widget-header").css("background-color","#ff4400");bindCommentClick()}})}
function bindCommentClick(){$(".commentitem").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();$("#gencommentsdlg").dialog("close");$("#remark").val($(this).text())});$(".ordercommentitem").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();$("#gencommentsdlg").dialog("close");$("#orderoption").val($(this).text())})}function applyComment(){$("#remark").val($("#generalcommentfield").val())}
function applyOrderComment(){$("#orderoption").val($("#generalcommentfield").val())}function getProdEntry(a){for(var b=productInformation.prods,c=0;c<b.length;c++){var e=b[c];if(parseInt(e.id)==a)return e}return null}function getProdProperties(a){a=getProdEntry(a);return null!=a?{name:a.longname,price:a.price,unit:a.unit}:"FEHLER!"}
function addProductToNewOrders(a,b,c,e,f,g,h,k,m){$("#remark").val("");"undefined"===typeof k&&(k=1);"undefined"===typeof h&&(h=0);var l=getProdProperties(a),p=l.name;l=calcTotalPriceOfProdAndExtras(l.price,c);void 0!==g&&null!==g&&(l=g=parseFloat(g).toFixed(2).replace(",","."));g=phases.getCurrentPhase();null!==m&&(g=m);neworders[neworders.length]={name:p,option:b,extras:c,prodid:a,price:l,changedPrice:e,togo:f,unit:h,unitamount:k,phase:g};showNewOrders();$("#remark").val("");enterpricedlgshown=
!1}
function group(a){var b=[],c=[],e=[],f={count:[],joinedvals:[],name:b,price:c,option:e,extras:[],prodids:[],origidxs:[],changedPrices:[],togos:[],units:[],unitamounts:[],phases:[]},g;for(g=0;g<a.length;g++){var h=a[g];b=h.name;c=h.price;e=h.option;var k=h.prodid,m=h.changedPrice,l=h.togo,p=h.unit,t=h.unitamount,q=h.phase,r=h.extras;h="";var n=[];if(null!=r)for(var u=0;u<r.length;u++)n[n.length]="+"+r[u].amount+"x "+toHtml(r[u].name);h=0<n.length?h+("<p>"+n.join("<br>")):"";r=b+"-"+e+"-"+h+"-"+p+"-"+
t+"G"+q;"NO"!==m&&(r=b+"-"+e+"-"+h+m+"G"+q);1==l&&(r+=" - To-Go");n=f.joinedvals.indexOf(r);0<=n?(f.count[n]+=1,idxarr=f.origidxs[n],idxarr[idxarr.length]=g,f.origidxs[n]=idxarr):(n=f.count.length,f.count[n]=1,f.joinedvals[n]=r,f.name[n]=b,f.price[n]=c,f.option[n]=e,f.extras[n]=h,f.prodids[n]=k,f.changedPrices[n]=m,f.togos[n]=l,f.units[n]=p,f.unitamounts[n]=t,f.phases[n]=q,f.origidxs[n]=[g])}return f}
function calcAndShowPriceOfNewOrders(){for(var a=0,b=groupedNewOrders.count.length-1;0<=b;b--){var c=groupedNewOrders.unitamounts[b],e=groupedNewOrders.price[b],f=groupedNewOrders.changedPrices[b];"NO"!==f&&(e=parseFloat(f));a+=groupedNewOrders.count[b]*e*c}a=a.toFixed(2);a=a.replace(".",decpoint);$("#neworderinfofield").html(a+" "+currency)}
function showNewOrders(){groupedNewOrders=group(neworders);for(var a="",b=groupedNewOrders.count.length-1;0<=b;b--){var c=groupedNewOrders.units[b],e=groupedNewOrders.unitamounts[b],f=groupedNewOrders.phases[b],g="";isUnitOfAmountTypeNotPieceNotVoucher(c)&&(g=e+g_units_arr[c].text+" ");e=toHtml(groupedNewOrders.name[b]);0<f&&(e+=" "+phases.getPhaseName(f));f=groupedNewOrders.option[b];var h=groupedNewOrders.count[b];e=1<h?"<span style='font-size: 23px;'>"+h.toString()+"x</span> "+g+e:g+e;g=groupedNewOrders.prodids[b];
""!==f&&(f="<p>"+toHtml(f)+"</p>");var k=groupedNewOrders.changedPrices[b];h=groupedNewOrders.togos[b];var m="",l=groupedNewOrders.extras[b];null!=l&&""!=l&&(m="<span style='font-size: 14px;'><i>"+l+"</i></span>");l="";"NO"!=k?(k=k.replace(".",decpoint)+" "+currency,isUnitOfAmountTypeNotPieceNotVoucher(c)&&(k+="/"+g_units_arr[c].text),l=0!=h?"<br> (<span class='priceatarticle'>"+k+"</span> - To-Go)":"<br> (<span class='priceatarticle'>"+k+"</span>)"):0!=h&&(l="<br> (To-Go)");a+='<div id="neworder_'+
g+"_"+b+'" class="ordereditem-item-new">'+e+f+m+l+"</div>"}$("#neworders").html(a);$("#remark").val("");calcAndShowPriceOfNewOrders();a=getTableid();updateLiveOrders(neworders,a);bindNewOrderItem();displayRightButtons()}
var roominfo=null,selectedroomindex=null,selectedtableindex=null,productInformation=null,allextras=null,selectedtypeid=null,selectedprodid=null,rightpaydesk=!1,sumupforcard=0,affiliatekey="",appid="",serverurl="",preferimgdesk=0,calcmodus=1,tableMapIsZoomed=!1,mainmenu=[],version="",loggedinUser="",payments="",hostTemplate="",WORKFLOW_DIGI_AND_WORK=0,WORKFLOW_DIGI=1,WORKFLOW_WORK=2,WORKFLOW_WORK_TRANSFER=3,productFilter=null,moveFromTableId=null,moveToRoomIndex=null,moveToTableId=null,panelMode="waiter",
returntoorder=1,genComments=null,usercandocashop=0,tableMapInFocus=0,tableMapWidth=0,tableMapHeight=0,performanceMeasureTimer=0,perfStartTime=0,PERFTIMER=5,perfStartTimeShowAllRooms=0,phases=null,W_SELALL=["Alles ausw\u00e4hlen","Select all","Elegir todo"],W_UNSELALL=["Alles abw\u00e4hlen","Unselect all","No elegir nada"],W_NO_PRODS_SELECTED=["Es wurden keine Produkte ausgew\u00e4hlt!","You have not chosen any products!","No ha seleccionado ning\u00fan producto!"],W_ONLY=["noch","only","s\u00f3lo"],
W_TO_PAY=["offen","to pay","a pagar"],P_CASHACTION_OK=["Kassenaktion abgeschlossen.","Action completed.","Acci\u00f3n terminado."],W_NO_VALID_PRICE=["Keine g\u00fcltige Zahl","No valid value","No es un n\u00famero valido"],W_NO_REORDER_VAR_PRICE=["Nur Produkte mit der Einheit 'St\u00fcck' k\u00f6nnen auf diese Weise nachbestellt werden.","Only products of unit 'Piece' can be reordered this way.","Un producto de esta unidad no se puede reordenado asi."];function setLanguage(a){}
$(document).ready(function(){phases=new Phases;phases.setLang(0);productFilter=selectedroomindex=null;doAjax("GET","php/contenthandler.php?module=admin&command=getWaiterSettings",null,insertWaiterConfig,"Fehler Konfigurationsdaten",SYNC);doAjax("GET","php/contenthandler.php?module=admin&command=getJsonMenuItemsAndVersion",null,saveMenuInfo,null,!0);getGeneralConfigItems();getTableMapPreferences();intervalGetItemsToPayAndRoomInfo(10);getMenuInBackground(60);getPayments(savePayments);getHostTemplate();
intervalCheckConnection(2);intervalGetPrinterStatus(5);intervalGetGeneralCommentsAndTablePref(10);intervalGetWaiterMessage(20);intervalFetchDaycode(10);updateLiveOrders(null,null);0==restaurantmode&&(changeRoom(-1),startProductDisplay());phases.bindPhaseBtns(!1)});function savePayments(a){payments=a.payments;hotelinterface=a.hotelinterface;guests=a.guests;internalguests=a.internalguests}
function intervalGetItemsToPayAndRoomInfo(a){setInterval(function(){getAndShowPayItems(!1);requestRoomInformation();requestOrderedInformation()},1E3*a)}function intervalGetGeneralCommentsAndTablePref(a){doAjax("GET","php/contenthandler.php?module=products&command=getAllGeneralComments",null,fillGenCommentsList,null,!0);setInterval(function(){doAjax("GET","php/contenthandler.php?module=products&command=getAllGeneralComments",null,fillGenCommentsList,null,!0);getTableMapPreferences()},1E3*a)}
function intervalGetWaiterMessage(a){doAjax("GET","php/contenthandler.php?module=admin&command=getWaiterMessage",null,fillWaiterMessage,null,!0);setInterval(function(){doAjax("GET","php/contenthandler.php?module=admin&command=getWaiterMessage",null,fillWaiterMessage,null,!0)},1E3*a)}function intervalFetchDaycode(a){setInterval(function(){doAjax("GET","php/contenthandler.php?module=admin&command=getDailycode",null,updateDailycode,!0)},1E3*a)}
function updateDailycode(a){"OK"===a.status&&(dailycode=a.msg,$(".daycodefield").html(toHtml(dailycode)))}function getMenuInBackground(a){setInterval(function(){requestProdInformation()},1E3*a)}
function insertWaiterConfig(a){if(1!=a.isUserLoggedIn)setTimeout(function(){document.location.href="index.html"},250);else{var b=a.config;setGlobalVars(a);usercandocashop=a.rightcashop;preferimgdesk=a.preferimgdesk;calcmodus=a.calcpref;rightpaydesk=a.rightpaydesk;returntoorder=b.returntoorder;billprintjobs=b.billprintjobs;1==b.showdaycode?($(".daycodeareamobile").show(),$(".daycodefield").html(toHtml(dailycode))):$(".daycodeareamobile").hide();1==usebarcode&&($("#barcode").show(),$("#barcode").val(""),
document.getElementById("barcode").focus());initializeOrderView()}}function fillGenCommentsList(a){"OK"!==a.status?"2"==a.code&&setTimeout(function(){document.location.href="logout.php"},250):genComments=a.msg}function fillWaiterMessage(a){"OK"===a.status&&(a=a.msg.trim(),""!=a?($("#waitermessagearea").html("<b>Nachricht: </b>"+toHtml(a).replaceAll("\n","<br>")),$("#waitermessagearea").show()):($("#waitermessagearea").html(""),$("#waitermessagearea").hide()))}
function initializeOrderView(){panelMode="waiter";initGui();clearProductsSelection();requestRoomInformation();requestProdInformation();bindMainMenuButton();bindRightButtons();0==restaurantmode&&$("#tablepanel").hide()}function getHostTemplate(){$.ajax({url:"customer/bon-bewirtungsvorlage.html?v=2.9.12",async:!1,success:function(a){hostTemplate=a},error:function(a){},cache:!1})}
function saveMenuInfo(a){1==a.loggedin?(loggedinUser=a.user,$("#loggedinuser").html("&nbsp;"+loggedinUser),$("#versioninfo").html(a.version),version=a.version,$.each(a.menu,function(b,c){mainmenu[mainmenu.length]={name:c.name,link:c.link}}),$("#mainmenubtn").show()):$("#mainmenubtn").hide()}
function bindMainMenuButton(){$("#selectiondialog").dialog({autoOpen:!1,modal:!0,height:400,buttons:{Anwenden:function(){$(this).dialog("close");applyExtras()}}});$("#unsentorderdlg").dialog({autoOpen:!1,modal:!0,height:400,buttons:{Nein:function(){$(this).dialog("close")},Ja:function(){$(this).dialog("close")}}});$("#actmenudlg").dialog({autoOpen:!1,modal:!0,height:400});$("#mainmenudlg").dialog({autoOpen:!1,modal:!0,height:400,width:200,position:{my:"right top",at:"right top",of:"body"},buttons:{Abbrechen:function(){$(this).dialog("close")}}});
$("#ordereditemdlg").dialog({autoOpen:!1,modal:!0,height:400,width:200});$("#moveItemdslg").dialog({autoOpen:!1,modal:!0,height:400,width:200});$("#mainmenubtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a="<div><ul class='mainmenuchoice'>";for(var b=0;b<mainmenu.length;b++)a+="<li id='mainmenu_"+b+"' class='mainmenuitem' >"+toHtml(mainmenu[b].name)+"</li>";a+="</ul></div>";$("#mainmenudlg").html(a);a=280+40*mainmenu.length;$("#mainmenudlg").dialog({autoOpen:!1,
modal:!0,height:a,width:200,position:{my:"right top",at:"right top",of:"body"},buttons:{Abbrechen:function(){$(this).dialog("close")}}});$("#mainmenudlg").dialog("open");$(".mainmenuitem").off("click").on("click",function(c){c.stopImmediatePropagation();c.preventDefault();c=parseInt(this.id.split("_")[1]);var e=mainmenu[c].link;$("#mainmenudlg").dialog("close");0<neworders.length?($("#unsentorderdlg").dialog({autoOpen:!1,modal:!0,height:400,buttons:{Nein:function(){$(this).dialog("close")},Ja:function(){$(this).dialog("close");
clearLiveOrders();setTimeout(function(){document.location.href=e},250)}}}),$("#unsentorderdlg").dialog("open")):(clearLiveOrders(),setTimeout(function(){document.location.href=e},250))})});bindCashButton();bindZeroReceiptButton()}function bindZeroReceiptButton(){$("#zeroreceiptbutton").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();startCreateAustriaZeroReceipt()})}
function startCreateAustriaZeroReceipt(){doAjax("POST","php/contenthandler.php?module=bill&command=austriazeroreceipt",null,handleCashActionResultDesktop,"Fehler Kassenaktion")}function handleCashActionResultDesktop(a){"OK"===a.status?alert("Abgeschlossen. Der Nullbeleg ist in der Kassenbonansicht einsehbar"):alert("Fehler: "+a.msg)}function goOrderDesk(){panelMode="waiter";initGui();clearNewOrderPrice();clearProductsSelection();requestProdInformation();requestOrderedInformation()}
function goPayDesk(){panelMode="paydesk";initGui();startCashProcess()}function initGui(){displayPanels();displayRightButtons()}
function displayPanels(){"waiter"===panelMode?(1==cashenabled||quickcash==QUICKCASH_YES?$("#panelmodetxt").html("Bestellung - Schnellkasse"):$("#panelmodetxt").html("Bestellung"),$("#groupchain").show(),$("#groupchoice").show(),$("#searchpanel").show(),1==usebarcode&&document.getElementById("barcode").focus(),$("#productspanel").show(),$("#remarkpanel").show(),$("#ordered").show(),$("oben").html(""),$("#oben").hide(),$("#unten").html(""),$("#unten").hide(),$("#paybuttonpanel").hide(),$("#billprintjobspanel").hide(),
$("#receiptpanel").hide()):($("#panelmodetxt").html("Kasse"),$("#groupchain").hide(),$("#groupchoice").hide(),$("#searchpanel").hide(),$("#productspanel").hide(),$("#remarkpanel").hide(),$("#ordered").hide(),$("oben").html(""),$("#oben").show(),$("#unten").html(""),$("#unten").show(),$("#goorderbtn").show(),$("#paybuttonpanel").show(),1==showreceiptinpaydesk&&$("#receiptpanel").show())}
function displayRightButtons(){$("#changetablebtn").hide();$("#tablerecordsbtn").hide();1==usercandocashop?$("#cashbutton").show():$("#cashbutton").hide();1==austriaenabled&&4==austriabind&&0==prodsOnReceiptList.length?$("#zeroreceiptbutton").show():$("#zeroreceiptbutton").hide();"waiter"===panelMode?(1==rightpaydesk&&0==cashenabled&&0==quickcash&&($("#paydeskbtn").show(),$("#phasesarea").show()),1==showphases?$("#phasesarea").show():$("#phasesarea").hide(),$("#neworderinfo").show(),$("#hostbutton").hide(),
$("#minuscheapest").hide(),$("#paydeskcash").hide(),$("#paydeskprint").hide(),$("#goorderbtn").hide(),workflowconfigfood!=workflowconfigdrinks&&(showtransferbtns=0),0<neworders.length&&(workflowconfigfood!=WORKFLOW_DIGI_AND_WORK&&workflowconfigfood!=WORKFLOW_WORK&&workflowconfigfood!=WORKFLOW_WORK_TRANSFER||1!=showtransferbtns||$("#workbtn").show(),workflowconfigfood!=WORKFLOW_DIGI_AND_WORK&&workflowconfigfood!=WORKFLOW_DIGI&&workflowconfigfood!=WORKFLOW_WORK_TRANSFER||1!=showtransferbtns||$("#sendNewOrders").show()),
null!=selectedtableindex&&0===neworders.length&&($("#changetablebtn").show(),$("#tablerecordsbtn").show())):($("#paydeskbtn").hide(),$("#phasesarea").hide(),$("#neworderinfo").hide(),$("#phasesarea").hide(),1==restaurantmode&&1==showhostprint&&($("#hostbutton").show(),1==allowminuscheapest?($("#minuscheapest").show(),bindMinusCheapestButton("desktop")):$("#minuscheapest").hide()),0==allowminuscheapest&&$("#minuscheapest").hide(),0<prodsaccounted.length?(0==forceprint&&$("#paydeskcash").show(),$("#paydeskprint").show(),
$("#goorderbtn").show()):($("#paydeskcash").hide(),$("#paydeskprint").hide()),$("#workbtn").hide(),$("#sendNewOrders").hide())}function clearNewOrderPrice(){var a="0.00 "+currency;a=a.replace(".",decpoint);$("#neworderinfofield").html(a);clearLiveOrders()}var e_prod=null,e_option=null,extrasManagement=new ExtrasManagement;
function showExtras(a,b){e_prod=a;e_option=b;extrasManagement.setAllExtras(a.extras);$("#selectiondialog").dialog({autoOpen:!1,modal:!0,height:400,buttons:{Anwenden:function(){$(this).dialog("close");applyExtras()}}});displayExtras();$("#selectiondialog").dialog("open")}
function displayExtras(){var a="<div><ul class='extraschoice'>";0!=requestPriceInExtras&&(a+='<li><input id="enterpriceextrasfield" type="text" placeholder="Preis" value="'+toHtml(presetPriceInExtras)+'" /></li>');a+=extrasManagement.renderExtras(null,null,!1);a+="</ul></div>";$("#selectiondialog").html(a);$(".ui-dialog-buttonset .ui-button").css("background-color","#44ff44");$(".ui-widget-header").css("background-color","#ff4400");bindExtra()}
function bindExtra(){$(".extraitem").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();extraClicked(parseInt(this.id.split("_")[1]))});$(".extraitemselected").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();extraClicked(parseInt(this.id.split("_")[1]))})}function extraClicked(a){!1!==requestPriceInExtras&&(presetPriceInExtras=$("#enterpriceextrasfield").val());extrasManagement.extraClicked(a);displayExtras()}
function applyExtras(){var a=extrasManagement.getAssignedExtras(),b=getProdProperties(e_prod.id),c=phases.getCurrentPhase();if(requestPriceInExtras){var e=$("#enterpriceextrasfield").val();e=e.trim();e=e.replace(decpoint,".");""!==e&&$.isNumeric(e)?(requestPriceInExtras=!1,presetPriceInExtras="",addProductToNewOrders(e_prod.id,e_option,a,e,0,e,b.unit,1,c)):alert(W_NO_VALID_PRICE[lang])}else addProductToNewOrders(e_prod.id,e_option,a,"NO",0,null,b.unit,1,c)}
function calcTotalPriceOfProdAndExtras(a,b){a=parseFloat(a);b=extrasManagement.calcPriceOfAssignedExtras(b,allextras);return totalPrice=parseFloat(a+b).toFixed(2)}var actcount=0,actprice=0,actname="",selectedEntry=null,actchangedprice=!1,actoption="",acttogo=0,actunit=0,actunitamount=1,actphase=0,origprice=0,countatdialogstart=0,CHANGE_ALL=0,CHANGE_ONE=1;
function bindNewOrderItem(){$(".ordereditem-item-new").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=parseInt(this.id.split("_")[2]);selectedEntry={count:groupedNewOrders.count[a],name:groupedNewOrders.name[a],price:groupedNewOrders.price[a],option:groupedNewOrders.option[a],extras:groupedNewOrders.extras[a],prodid:groupedNewOrders.prodids[a],origidxs:groupedNewOrders.origidxs[a],changedPrices:groupedNewOrders.changedPrices[a],togos:groupedNewOrders.togos[a],
unit:groupedNewOrders.units[a],unitamount:groupedNewOrders.unitamounts[a],phase:groupedNewOrders.phases[a]};acttogo=groupedNewOrders.togos[a];countatdialogstart=actcount=groupedNewOrders.count[a];actname=groupedNewOrders.name[a];actchangedprice=groupedNewOrders.changedPrices[a];actoption=groupedNewOrders.option[a];actunit=groupedNewOrders.units[a];actunitamount=groupedNewOrders.unitamounts[a];actphase=groupedNewOrders.phases[a];origprice=groupedNewOrders.price[a];actprice="NO"===actchangedprice?origprice:
actchangedprice;insertDataIntoActDialog(!0);a=400;1==rightchangeprice&&(a=600);$("#actmenudlg").dialog({autoOpen:!1,modal:!0,height:a,width:600,buttons:{Abbrechen:function(){$(this).dialog("close")},"L\u00f6schen":function(){$(this).dialog("close");delNewOrderItem()},"Alle \u00e4ndern":function(){$(this).dialog("close");changeAllNewOrders()},"Einen Artikel \u00e4ndern":function(){$(this).dialog("close");changeOneNewOrder()}}});isUnitOfAmountTypeNotVoucher(actunit)?$("#actareaforproducts").show():
$("#actareaforproducts").hide();$(".ui-dialog-buttonset .ui-button").css("font-weight","bold");$(".ui-dialog-buttonset .ui-button").css("color","black");$(".ui-dialog-buttonset .ui-button:nth-child(2)").css("background-color","#ff0000");$("#actmenudlg").dialog("open")})}function getDiscountButton(a,b){a+="%";""!=b.trim()&&(a=toHtml(b));return a}
function insertDataIntoActDialog(a){$("#actdiscount1btn").html(getDiscountButton(discount1,discountname1));$("#actdiscount2btn").html(getDiscountButton(discount2,discountname2));$("#actdiscount3btn").html(getDiscountButton(discount3,discountname3));$("#actcountno").html(actcount+"x");$("#actname").html(actname);var b=parseFloat(actprice).toFixed(2).replace(".",decpoint),c=b+" "+currency;isUnitOfAmountTypeNotPieceNotVoucher(actunit)&&(c+="/"+g_units_arr[actunit].text);$("#actpriceinfo").html(c);$("#actpricefield").val(b);
$("#actremarkfield").val(actoption);a&&$("#actnumberentryfield").val(actcount);0==acttogo?($("#togoicon").hide(),$("#notogoicon").show()):($("#togoicon").show(),$("#notogoicon").hide());1==rightchangeprice?($("#actdiscount").show(),$("#actprice").show()):($("#actdiscount").hide(),$("#actprice").hide());bindActBtn()}
function bindActBtn(){$("#actnumberentryfield").off("keyup").on("keyup",function(a){a=$("#actnumberentryfield").val().trim();""!=a&&$.isNumeric(a)?0<=a&&1E3>=a?(actcount=a,insertDataIntoActDialog(!1)):insertDataIntoActDialog(!0):(actcount=countatdialogstart,insertDataIntoActDialog(!1))});$("#actremarkfield").off("keyup").on("keyup",function(a){actoption=$("#actremarkfield").val()});$(".actbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id;"actminusbtn"===
a?(0<actcount&&actcount--,$("#actnumberentryfield").val(actcount)):"actplusbtn"===a?(actcount++,$("#actnumberentryfield").val(actcount)):"actdiscount1btn"===a?(actprice=origprice-origprice*discount1/100,a=actprice.toFixed(2).replace(".",decpoint),$("#actpricefield").val(a),$("#actpriceinfo").html(a+" "+currency)):"actdiscount2btn"===a?(actprice=origprice-origprice*discount2/100,a=actprice.toFixed(2).replace(".",decpoint),$("#actpricefield").val(a),$("#actpriceinfo").html(a+" "+currency)):"actdiscount3btn"===
a?(actprice=origprice-origprice*discount3/100,a=actprice.toFixed(2).replace(".",decpoint),$("#actpricefield").val(a),$("#actpriceinfo").html(a+" "+currency)):"acttogobtn"===a&&(acttogo=1-acttogo);insertDataIntoActDialog(!0)})}function changeAllNewOrders(){actionNewOrderConfirm(CHANGE_ALL)}function changeOneNewOrder(){actionNewOrderConfirm(CHANGE_ONE)}function delNewOrderItem(){actcount=0;actionNewOrderConfirm(CHANGE_ALL)}
function isPriceChangedInDialog(a){const b=$("#actpricefield").val().trim().replace(",",".");if(""==b||!$.isNumeric(b))return!1;a=getProdEntry(a).price;return b==a?!1:!0}
function actionNewOrderConfirm(a){var b=selectedEntry,c=isPriceChangedInDialog(b.prodid),e=$("#actpricefield").val().trim().replace(",",".");if(1==c){if(99999.99<e){alert("Maximaler Preis f\u00fcr das Produkt \u00fcberschritten");return}if(""==e)e="NO";else if($.isNumeric(e))e=parseFloat(e).toFixed(2),actprice=parseFloat(e),$("#actpricefield").val("");else{alert("Es wurde ein falsches Zahlenformat angegeben");return}}else 1!=getProdEntry(b.prodid).unit&&(e="NO");if(a==CHANGE_ONE){var f=b.origidxs;
neworders[f[0]].option=$("#actremarkfield").val();neworders[f[0]].changedPrice=e;neworders[f[0]].togo=acttogo;neworders[f[0]].phase=actphase}else for(f=b.origidxs,c=0;c<f.length;c++)a=f[c],neworders[a].option=$("#actremarkfield").val(),neworders[a].changedPrice=e,neworders[a].togo=acttogo,neworders[a].phase=actphase;$("#actremarkfield").val("");$("#actnumberentryfield").val("");a=actcount-b.count;if(0>a)for(e=0-a,f=b.origidxs,c=0;c<e;c++){var g=f.pop();neworders.splice(g,1)}if(0<a){f=b.origidxs;c=
f[0];b=neworders[c].prodid;e=neworders[c].changedPrice;f=neworders[c].togo;g=neworders[c].option;var h=neworders[c].extras,k=neworders[c].price,m=neworders[c].unit,l=neworders[c].unitamount,p=neworders[c].phase;for(c=0;c<a;c++)addProductToNewOrders(b,g,h,e,f,k,m,l,p)}showNewOrders()}var taxtype="normal",prodsToPayList=[],prodsToPayListGrouping=[],prodsOnReceiptList=[],prodsOnReceiptListGrouping=[],prodsaccounted=[],doPrint=!1,showItemsPerPrintJob=!1;
function startCashProcess(){prodsaccounted=[];displayRightButtons();getAndShowPayItems(!0)}
function getAndShowPayItems(a){if("paydesk"===panelMode){var b=0;null!=selectedroomindex?0<=selectedroomindex?null!=selectedtableindex?(b=roominfo.roomstables[selectedroomindex].tables[selectedtableindex].id,taxtype="normal"):b=null:(tabeid=0,taxtype="togo"):b=null;showItemsPerPrintJob=!1;1==billprintjobs||2==billprintjobs&&0==b?(showItemsPerPrintJob=!0,$("#billprintjobspanel").show()):$("#billprintjobspanel").hide();null!=b?a?doAjax("GET","php/contenthandler.php?module=queue&command=getJsonProductsOfTableToPay",
{tableid:b},showProductsToPayInit,"Fehler bei der Daten\u00fcbermittlung",!0):doAjax("GET","php/contenthandler.php?module=queue&command=getJsonProductsOfTableToPay",{tableid:b},showProductsToPayCycle,"Fehler bei der Daten\u00fcbermittlung",!0):(prodsToPayList=[],displayProdsToPayForTable(),displayProdsOnReceipt())}}function showProductsToPayInit(a){showProductsToPay(a,!0)}function showProductsToPayCycle(a){showProductsToPay(a,!1)}
function showProductsToPay(a,b){if("OK"!==a.status&&(alert("Fehler: "+a.msg),4==a.code)){setTimeout(function(){document.location.href="index.html"},250);return}prodsToPayList=a.msg;fillProdByPrintJobsList(prodsToPayList);0===a.msg.length&&1==returntoorder?(unZoomTableMap(),goOrderDesk()):(displayProdsToPayForTable(),displayProdsOnReceipt());b&&1==allprodstoreceipt&&doPayAllActions()}
function putItemInSortedListToReceipt(a){if(void 0===prodsToPayListGrouping.sortedset)console.log("sortedset is empty - so no putItemInSortedListToReceipt can be performed");else for(var b=0;b<prodsToPayListGrouping.sortedset.length;b++)for(var c=prodsToPayListGrouping.sortedset[b],e=c.ids,f=0;f<e.length;f++)if(e[f]==a){increaseAccountedNumber(c);return}}
function displayProdsToPayForTable(){bindHostButton("#hostbutton");if(0==prodsToPayList.length)$("#oben").html("Keine weiteren Artikel vorhanden.");else{prodsToPayListGrouping=new Grouping(prodsToPayList,createHashOfPayableItem);prodsToPayListGrouping.group();var a=prodsToPayListGrouping.outputList(createPayableItemListElement);$("#oben").html(a)}$(".payable").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();b=this.id;var c=$(".payable").index(this);if(void 0===
prodsToPayListGrouping.sortedset)console.log("sortedset is empty - so no payable can be added");else{c=prodsToPayListGrouping.sortedset[c];var e=aProdToPayIsClicked(c);updateAccounted(b,e,c.count);displayProdsOnReceipt()}});$("#payall").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();doPayAllActions()});if(showItemsPerPrintJob)$(".payallofprintjob").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();b=this.id.split("_")[1];b=prodsByPrintjob[b];
for(var c=0;c<b.length;c++)putItemInSortedListToReceipt(b[c].id);displayProdsToPayForTable();displayProdsOnReceipt()});$("#paydeskcash").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();doPrint=!1;1==showpayments?displayPayments():payWithoutPaymentDlg()});$("#paydeskprint").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();doPrint=!0;1==showpayments?displayPayments():payWithoutPaymentDlg()})}
function doPayAllActions(){void 0===prodsToPayListGrouping.sortedset?console.log("sortedset is empty - so no doPayAllActions can be performed"):(0<prodsToPayListGrouping.sortedset.length&&prodsToPayListGrouping.sortedset.forEach(function(a){var b=a.count;createHashOfPayableItem(a);setAccountedNumber(a,b)}),displayProdsToPayForTable(),displayProdsOnReceipt())}
function displayPayments(){var a='<div id="paym_1" class="paymentitem" >'+payments[0].name+"</div>";a+="<br><hr><br>";for(var b=0;b<payments.length;b++){var c=payments[b],e=c.id;c=c.name;2==e&&1==showpayment2&&(a+='<div id="paym_'+e+'" class="paymentitem" >'+c+"</div>");3==e&&1==showpayment3&&(a+='<div id="paym_'+e+'" class="paymentitem" >'+c+"</div>");4==e&&1==showpayment4&&(a+='<div id="paym_'+e+'" class="paymentitem" >'+c+"</div>");5==e&&1==showpayment5&&(a+='<div id="paym_'+e+'" class="paymentitem" >'+
c+"</div>");6==e&&1==showpayment6&&(a+='<div id="paym_'+e+'" class="paymentitem" >'+c+"</div>");7==e&&1==showpayment7&&(a+='<div id="paym_'+e+'" class="paymentitem" >'+c+"</div>");8==e&&1==showpayment8&&(a+='<div id="paym_'+e+'" class="paymentitem" >'+c+"</div>")}a+='<div id="paym_cancel" class="paymentcancel" >'+P_CANCEL[lang]+"</div>";$("#selectiondialog").html('<table id ="calculatorarea" style="border: 1px solid black;display:none;width:100%;"><tr><td><span id=topaytxt>Zahlen: </span><td><i><b><span id=topayval>0,00</span></b></i></tr><tr><td><span id=haspaidtxt>Bezahlt: </span><td style="width:100px;color:yellow;"><input type="text" id="haspaid" value=""  placeholder="" style="width:150px;"/></tr><tr><td><span id=tiptxt>Trinkg.: </span><td style="width:100px;color:yellow;"><input type="text" id="tipfield" value="" placeholder="" style="width:150px;"/><tr><td><span id="rettxt">Zur\u00fcck: </span><td><i><b><span id="topayback" style="background-color:#ffff99;">0,00</span></b></i><span id=curtopay2></span></td></tr></tr><tr><td colspan=5><button id="calcreturnbtn" type="submit" ><span id="calcreturn">Berechne</span></button></tr></table>'+
a);setCalcModusBtn();a=$("#priceinreceipt2").html().replace(".",decpoint);fillValuesInCalc(a,decpoint,currency);bindCalcReturn();a=600;1==paymentconfig&&(a=380);$("#selectiondialog").dialog({autoOpen:!1,modal:!0,height:a,buttons:{Abbrechen:function(){$(this).dialog("close")}}});$("#selectiondialog").dialog("open");bindPayment()}function payWithoutPaymentDlg(){startPayProcess(1,"","","",null)}
function bindPayment(){$(".paymentcancel").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();$("#selectiondialog").dialog("close")});$(".paymentitem").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();currentPaymentId=a=this.id.split("_")[1];$("#selectiondialog").dialog("close");if(currentPaymentId==PAYMENT_HS3||currentPaymentId==PAYMENT_GUEST)$("#hoteldialog").dialog({autoOpen:!1,modal:!0,height:400,width:500,buttons:{Abbrechen:function(){$(this).dialog("close")}}}),
""!==$("#tipfield").val().trim()?alert("Bei Gast- oder Hotelbuchung ist keine Trinkgeldbezahlung vorgesehen."):($("#hoteldialog").dialog("open"),$("#roomguesttextfield").val(""),bindhotelinterface(currentPaymentId));else{var b=checkAndCalcRightTip(decpoint,calcmodus);"OK"!==b.status?alert("Problem bei Trinkgeldberechnung: "+b.msg):startPayProcess(a,"","","",b.value)}})}
function bindhotelinterface(a){generateGuestResult($("#roomguesttextfield").val(),!1,a);$("#roomguesttextfield").off("keyup").on("keyup",function(b){generateGuestResult($("#roomguesttextfield").val(),!1,a)});$("#paym_hotel").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();$("#hotelroomfoundguest").data("reservation");$("#hotelroomfoundguest").data("guest");var c=$("#hotelroomselection").find(":selected").val();if(void 0!=c){b=guests[c];var e="";currentPaymentId==
PAYMENT_GUEST&&(b=internalguests[c],e=b.id);startPayProcess(currentPaymentId,b.reservationid,b.object+" - "+b.guest,e,null);$("#hoteldialog").dialog("close")}else alert("Kein Gast ausgew\u00e4hlt")})}
function generateGuestResult(a){a=a.trim().toLowerCase();if(""===a)$("#hotelroomselection").html("");else{var b="",c=!1;$.each(guests,function(e,f){var g=f.object;f=f.guest;var h=0<=g.toLowerCase().indexOf(a),k=0<=f.toLowerCase().indexOf(a);if(h||k)c?b+='<option value="'+e+'" >'+toHtml(g+" - "+f)+"</option>":(c=!0,b+='<option value="'+e+'" selected>'+toHtml(g+" - "+f)+"</option>")});$("#hotelroomselection").html(b)}}
function updateAccounted(a,b,c){b===c?($("#"+a).removeClass("paystillopen"),$("#"+a).removeClass("payallaccounted"),$("#"+a).removeClass("payitemnormborder"),$("#"+a).addClass("payallaccounted"),$("#"+a).addClass("payitemoffborder")):($("#"+a).removeClass("paystillopen"),$("#"+a).removeClass("payallaccounted"),$("#"+a).removeClass("payitemoffborder"),$("#"+a).addClass("paystillopen"),$("#"+a).addClass("payitemnormborder"));0===b?$("#"+a+" .payitemaccounted").html(""):$("#"+a+" .payitemaccounted").html(b)}
function getProdAccountedEntry(a){a=createHashOfPayableItem(a);for(var b=0;b<prodsaccounted.length;b++){var c=prodsaccounted[b];if(a===c.hash)return c}return null}function increaseAccountedNumber(a){var b=getProdAccountedEntry(a);null!==b?b.count+=1:(a={hash:createHashOfPayableItem(a),count:1},prodsaccounted[prodsaccounted.length]=a)}
function setAccountedNumber(a,b){var c=getProdAccountedEntry(a);null!==c?c.count=b:(a={hash:createHashOfPayableItem(a),count:b},prodsaccounted[prodsaccounted.length]=a)}function aProdToPayIsClicked(a){var b=getProdAccountedEntry(a);if(null!==b)return b.count<a.count?(b.count+=1,b.count):b.count=0;a={hash:createHashOfPayableItem(a),count:1};prodsaccounted[prodsaccounted.length]=a;return 1}
function displayProdsOnReceipt(){createProdsOnReceiptList();prodsOnReceiptListGrouping=new Grouping(prodsOnReceiptList,createHashOfPayableItem);prodsOnReceiptListGrouping.group();createAllEntriesInReceipt()}
function createHashOfPayableItemWithoutTax(a){var b=a.longname;"A"!=a.pricelevelname&&(b+=" ("+a.pricelevelname+")");b+=" - "+parseFloat(a.price).toFixed(2).replace(".",decpoint);1==a.togo&&(b="To-Go: "+b);var c=[];a=a.extras;for(var e=0;e<a.length;e++)c[c.length]="+ "+toHtml(a[e]);c="<p>"+c.join("<br>");return toHtml(b)+c}function createHashOfPayableItem(a){var b="{{"+parseFloat(a.tax).toFixed(2).replace(".",decpoint)+"}}";return createHashOfPayableItemWithoutTax(a)+toHtml(b)}
function createPayableItemListElement(a){var b="",c=1;"count"in a&&1<a.count&&(b=a.count+"x ",c=a.count);var e=!1,f=getProdAccountedEntry(a),g="";null!==f&&(0!=f.count&&(g=f.count),f.count==c&&(e=!0));e?0==preferimgdesk?a='<div id="payable_'+a.id+'" class="payitem payitemoffborder payable payallaccounted"><div class=\'payitemmain\'>'+b+createHashOfPayableItemWithoutTax(a)+"</div><div class='payitemaccounted'>"+g+"</div></div>":(c="php/contenthandler.php?module=products&command=getprodimage&prodid="+
a.prodid+"&size=m",c=" style=\"background-image: url('"+c+"'); background-size: cover; background-repeat: no-repeat;  background-position: center center; \" ",b="<span class='whitebackground'>"+b+createHashOfPayableItemWithoutTax(a)+"</span>",a='<div id="payable_'+a.id+'" class="payitem payitemoffborder payable payallaccounted" '+c+"><div class='payitemmain'>"+b+"</div><div class='payitemaccounted'>"+g+"</div></div>"):0==preferimgdesk?a='<div id="payable_'+a.id+'" class="payitem payitemnormborder payable paystillopen"><div class=\'payitemmain\'>'+
b+createHashOfPayableItemWithoutTax(a)+"</div><div class='payitemaccounted'>"+g+"</div></div>":(c="php/contenthandler.php?module=products&command=getprodimage&prodid="+a.prodid+"&size=m",c=" style=\"background-image: url('"+c+"'); background-size: cover; background-repeat: no-repeat;  background-position: center center; \" ",b="<span class='whitebackground'>"+b+createHashOfPayableItemWithoutTax(a)+"</span>",a='<div id="payable_'+a.id+'" class="payitem payitemnormborder payable paystillopen" '+c+"><div class='payitemmain'>"+
b+"</div><div class='payitemaccounted'>"+g+"</div></div>");return a}function createOnReceiptItemListElement(a){var b="";"count"in a&&1<a.count&&(b=a.count+"x ");return'<div id="payable_'+a.id+'" class="payitem onreceipt">'+b+createHashOfPayableItem(a)+"</div>"}
function getProdOfAllProdsWithHash(a){if(void 0===prodsToPayListGrouping.sortedset)return console.log("sortedset is empty - so no getProdOfAllProdsWithHash can be performed"),null;for(var b=prodsToPayListGrouping.sortedset,c=0;c<b.length;c++){var e=b[c];if(createHashOfPayableItem(e)===a)return e}return null}
function createProdsOnReceiptList(){prodsOnReceiptList=[];for(var a=0;a<prodsaccounted.length;a++){var b=prodsaccounted[a],c=getProdOfAllProdsWithHash(b.hash);for(j=0;j<b.count;j++)prodsOnReceiptList[prodsOnReceiptList.length]=clonePayableItem(c)}}function clonePayableItem(a){return{extras:a.extras,id:a.id,ids:a.ids,longname:a.longname,price:a.price,pricelevelname:a.pricelevelname,prodid:a.prodid,tax:a.tax,togo:a.togo,unit:a.unit,unitamount:a.unitamount}}
function createAllEntriesInReceipt(){for(var a=[],b=0;b<prodsOnReceiptList.length;b++){var c=prodsOnReceiptList[b];a=addEntryOrIncreaseCount(a,{prodid:c.prodid,queueid:c.id,longname:c.longname,price:c.price,tax:c.tax,togo:c.togo,extras:c.extras,pricelevelname:c.pricelevelname})}b=createReceiptHeader();b+=generateProdPart(decpoint,a);a=$("#info-page").data("usstGerVal");"togo"==$("#info-page").data("taxtype")&&(a=$("#info-page").data("togoTaxGerVal"));c=listTaxesBasedOnUntenList(decpoint);b+=createReceiptFooter(a,
lang,c);showHostTemplate&&(b+=hostTemplate);a="<table><br>"+b+"</table>";$("#receiptpanel").html(a);calcSum();a=getTableid();updateLivePayOrders(prodsOnReceiptList,a);a=$("#receiptpart").html();$("#info-page").data("receipthtml",a);displayRightButtons()}function getTableName(){return null!=selectedtableindex?roominfo.roomstables[selectedroomindex].tables[selectedtableindex].name:"-1"==selectedroomindex?"Zum Mitnehmen":null}
function createReceiptHeader(){return genCreateReceiptHeader(0,"",getTableName(),loggedinUser,currency,"",null)}function createReceiptFooter(a,b,c){return genCreateReceiptFooterNoSum(a,0,"",c)}function getQueueIdsDueToCountOfItem(a){var b=[],c=a.hash;a=a.count;for(var e=0;e<prodsToPayList.length;e++){var f=prodsToPayList[e];if(createHashOfPayableItem(f)===c&&(b[b.length]=f.id,b.length>=a))break}return b}
function _getTableId(){var a=0;-1!=selectedroomindex&&(a=null!=selectedtableindex?roominfo.roomstables[selectedroomindex].tables[selectedtableindex].id:0);return a}
function startPayProcess(a,b,c,e,f){getTableName();var g=_getTableId();$("#info-page").data("usst");"togo"==$("#info-page").data("taxtype")&&$("#info-page").data("togotax");checkForLogIn();for(var h=[],k=0;k<prodsaccounted.length;k++){var m=prodsaccounted[k];0!=m.count&&$.merge(h,getQueueIdsDueToCountOfItem(m))}h=h.join();a={ids:h,tableid:g,paymentid:a,declareready:1,host:showHostTemplate?1:0,reservationid:b,guestinfo:c,intguestid:e,camefromordering:1};null!==f&&(a.tip=f);$.ajax({type:"POST",dataType:"json",
data:a,url:"php/contenthandler.php?module=queue&command=declarePaidCreateBillReturnBillId",async:!1,success:function(l){showHostTemplate=!1;var p=l.msg;"ERROR"!=l.status?(billid=p.billid,billdate=p.date,0>billid?alert("Fehler! Wurden Produkte ausgew\u00e4hlt? Bitte erneut versuchen. Error code: "+billid):(requestRoomInformation(),l=$("#info-page").data("billlanguage"),$("#billid").html(P_ID[l]+billid),$("#billdate").html(billdate),doPrint&&("s"===$("#info-page").data("payPrintType")?printBill(billid):
($("#oben").hide(),l="<table>"+$(".receipttable").html()+"</table>",printContent(l))),cheaptestAlreadySubtracted=!1,startCashProcess())):alert("Fehler: "+p)},error:function(l){alert("Sorry, there was a problem! "+l)}})}
var P_DESCR=["Beschreibung","Description","Descripci\u00f3n"],P_PRICE=["Preis","Price","Precio"],P_TOTAL=["Total","Total","Total"],P_ID=["Id:","Id:","Id:"],P_ROOMSEL=["Raumauswahl","Room selection","Selecci\u00f3n de espacio"],P_PAYDESK_ACTIONS=["Kassenaktionen","Paydesk actions","Acciones de caja"],P_BAR_INPUT=["Bareinlage/-auslage","Input and output money","Insertar/Extrahir dinero"],P_BAR_GET=["Barentnahme","Take money","Sacar dinero"],P_BAR_SUM=["Einnahmen","Revenue","Cobro"],P_AUSTRIA_ZERO_RECEIPT=
["Nullbeleg erstellen (RKSV/\u00d6sterreich)","Create 'Nullbeleg' (RKSV/Austria)","Crear 'Nullbeleg' (RKSV/Austria)"],P_TITLE=["Kasse","Paydesk","Caja"],P_TABLE=["Tisch","Table","Mesa"],P_TABLE_SEL=["Tischauswahl","Select table","Qu\u00e9 mesa?"],P_NOT_PAID=["Ausstehend f\u00fcr ","Not paid for ","Impagado para "],P_OPS=["Operationen","Operations","Operaciones"],P_ALL=["Alles","All","Todo"],P_ONLY_MY_JOBS=["Zeige nur meine Bestellungen","Show only my orders","Mostrar s\u00f3lo mis pedidos"],P_CONTENT_RECEIPT=
["Inhalt Kassenbon","Content of receipt","Contenido del tique"],P_ONLY_PAY=["Nur Zahlung","Only pay","Solo pagar"],P_PAY_PRINT=["Bondruck","Pay+Print","Pagar+Imprimir"],P_CHANGE_CALC=["Wechselgeldrechner:","Change Calculator:","Calculadora de Cambio:"],P_TOTALSUM=["Summe","Sum","Total"],P_CHOOSE_PAYWAY=["Auswahl der Zahlungsart:","Selection of method of payment:","Selecci\u00f3n del modo de pago:"],P_CANCEL=["Abbrechen","Cancel","Cancelar"],P_CASHTAKEOUT=["Barentnahme aus der Kasse","Cash take-out",
"Sacar dinero"],P_CASHTAKIN=["Barein-/auslage in/aus Kasse","Cash insert/extract","Insertar/exportar dinero"],P_AMOUNT=["Betrag:","Amount:","Valor:"],P_OVERVIEW=["\u00dcbersicht Kellnerkasse","Overview waiter purse","Resumen cartera de bolsillo"],P_PUT_IN=["Einlegen/Entnehmen","Insert/Take out","Insertar"],P_TAKE_OUT=["Entnehmen","Take out","Sacar"],P_OVERV_DETAILS=["Diese \u00dcbersicht zeigt die Einnahmen durch den Kellner pro Zahlungsweg seit der letzten Tageslosung sowie als weiteren Wert den Kassenstand unter Ber\u00fccksichtigung der eigenen Eingaben und Entnahmen.",
"This overview contains the amount of money of this waiter since the last closing as well as the total amount of money including the own cash insert and take-out actions.","Este resumen contiene todo el dinero del camarero, y tambi\u00e9n el dinero incluido con acciones de insertar y sacar."],P_CASH_SUM=["Bewirtungseinnahmen (ohne Ein-/Auslagen):","Cash by payment (without inserts/take-outs):","Cobro (sin tomas/entradas):"],P_INCLUDE_OWN=["<b>Bar</b>bestand inkl. eigener Kassenein-/auslagen:","Cash incl. own cash insert/take-outs:",
"Cash  incl. tomas y entradas proprias:"],P_NO_ELEM=["Keine Rechnungselemente","No items selected","Ning\u00fan producto selecionado"],P_NO_ELEM_DETAILS=["Es wurden keine abrechenbaren Produkte festgelegt (der Bon ist leer!).","There are no selected items. The receipt is empty!","No hay ning\u00fan elemento seleccionado para pagar."];P_CASHACTION_OK=["Kassenaktion abgeschlossen.","Action completed.","Acci\u00f3n terminado."];
var P_NAV=["Navigation","Navigation","Navigaci\u00f3n"],P_ORDER_ACTION=["-> Bestellansicht","-> Order view","-> Vista de Orden"],P_TO_PAY=["Zu zahlen: ","To pay: ","Pagar total: "],P_PAY_RETURN=["Zur\u00fcck: ","Return: ","Torna: "],P_CALC_PAYBACK=["Berechne","Calculate","Calcular"],P_HAS_PAID=["Bezahlt: ","Paid: ","Pagado: "],P_TOGO=["Au\u00dfer-Haus-Verkauf","Sale with Tax No 2","Venta IVA 2"],P_TIP=["nur Trinkg.: ","Only tip: ","Solo prop.: "],P_TOTAL_INCL_TIP=["Zielbetrag:","Target pay:","Quiere pagar:"],
CALC_TIP_TXT=["Angabe extra Trinkg.","Do Tip separate","Propina individual"],CALC_TOTAL_TXT=["Angabe inkl. Trinkg.","Do Tip incl.","Propina incl."],P_GUESTS=["G\u00e4ste","Guests","Habitaciones"],P_OF_WORK_RECEIPT=[" von Arbeitsbon ","of work receipt "," del ticket de trabajo "],P_OF_ORDER_JOB=[" von Lieferauftrag "," of Order/Delivery "," de la Entrega "],P_FOR=["f\u00fcr","for","para"],P_BILL_TITLE=["Rechnung","Bill","Factura"],CALC_NONE=0,CALC_TOTAL=1,CALC_TIP=2,showHostTemplate=!1,guests=[],internalguests=
[],hotelinterface=0,PAYMENT_CARD=2,PAYMENT_HS3=7,PAYMENT_GUEST=8,currentPaymentId=7,showpayments=1,showpayment2=1,showpayment3=1,showpayment4=1,showpayment5=1,showpayment6=1,showpayment7=1,showpayment8=1,forceprint=0,showhostprint=1,billprintjobs=0,prodsByPrintjob=[],prodsByOrder=[],currentSelectedIsTogo=!1,allprodstoreceipt=usercandocashop=0,deskviewname="",lastCalcBruttoSum=0,cheaptestAlreadySubtracted=!1,allowminuscheapest=0,showreceiptinpaydesk=1,showonlymyjobscheck=0,usershowonlymyjobs=0,austriaenabled=
0,austriabind=0,cancelinpaydesk="";function getGeneralConfigItems(){doAjax("GET","php/contenthandler.php?module=admin&command=getGeneralConfigItems",null,insertGeneralConfigItems,"Fehler Konfigurationsdaten",SYNC)}function getPayments(a){doAjax("GET","php/contenthandler.php?module=admin&command=getPayments",null,a,"Fehler Zahlungswege")}function toHtmlInPaydesk(a){return void 0===a||null==a?"":"string"===typeof a?a.replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;"):a}
function insertGeneralConfigItems(a){if("OK"===a.status){a=a.msg;decpoint=a.decpoint;$("#info-page").data("decpoint",a.decpoint);currency=a.currency;usercandocashop=a.usercandocashop;allprodstoreceipt=a.allprodstoreceipt;deskviewname=a.deskviewname;austriaenabled=a.austria;austriabind=a.austriabind;var b=a.tax,c=b.replace(".",decpoint);$("#info-page").data("usstGerVal",c);$("#info-page").data("usst",b);b=a.togotax;c=b.replace(".",decpoint);$("#info-page").data("togoTaxGerVal",c);$("#info-page").data("togotax",
b);$("#info-page").data("companyinfo",a.companyinfo);$("#info-page").data("payPrintType",a.payprinttype);$("#info-page").data("currency",a.currency);$("#info-page").data("billlanguage",a.billlanguage);$("#info-page").data("userlanguage",a.userlanguage);receiptfontsize=parseInt(a.receiptfontsize);$("#receiptpart").css("font-size",receiptfontsize+"px");paymentconfig=a.paymentconfig;showpayments=a.showpayments;showpayment2=a.showpayment2;showpayment3=a.showpayment3;showpayment8=a.showpayment8;showpayment7=
a.showpayment7;showpayment6=showpayment5=showpayment4=0;forceprint=a.forceprint;$("#curtopay2").html(" "+a.currency);workflowconfigfood=a.workflowconfig;workflowconfigdrinks=a.workflowconfigdrinks;digigopaysetready=a.digigopaysetready;showhostprint=a.showhostprint;restaurantmode=a.restaurantmode;billprintjobs=a.billprintjobs;sumupforcard=a.sumupforcard;affiliatekey=a.affiliatekey;appid=a.appid;serverurl=a.serverurl;allowminuscheapest=a.allowminuscheapest;showreceiptinpaydesk=parseInt(a.showreceiptinpaydesk);
showonlymyjobscheck=parseInt(a.showonlymyjobscheck);usershowonlymyjobs=parseInt(a.usershowonlymyjobs);cancelinpaydesk=a.cancelinpaydesk;serverurl.endsWith("/")&&(serverurl=serverurl.substr(0,serverurl.length-1));$("#desktopviewname").html(deskviewname);setLanguage(a.userlanguage)}else $("#contentpart").hide(),setTimeout(function(){document.location.href="index.html"},250)}
function addEntryOrIncreaseCount(a,b){var c,e=!1,f=b.prodid+"-"+b.extras.join("_")+b.price+"-"+b.pricelevelname+"#"+b.tax+"_"+b.togo;for(c=0;c<a.length;c++){var g=a[c];g[2]==f&&(g[0]+=1,e=!0)}e||a.push([1,b,f]);return a}
function genCreateReceiptHeader(a,b,c,e,f,g,h){e=P_WAITER[a]+" "+e;b="<tr><td colspan=6>&nbsp;</tr><tr><td colspan=4>"+(P_TABLE[a]+" "+c+'\t\t\t<td id="billid" colspan=2 style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;">ID:'+b+'</tr><tr><td colspan=4>&nbsp;<td id="billdate" colspan=2 style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;"></tr>');b+="<tr><td colspan=6>"+e+"</tr><tr><td colspan=6>&nbsp</tr>";""!=g&&(b+="<tr><td colspan=6>Gast: "+
toHtmlInPaydesk(g)+"</tr>",b+="<tr><td colspan=6>&nbsp</tr>");null!=h&&(b+="<tr><td colspan=6>Zahlungsweg: "+h+"</tr>",b+="<tr><td colspan=6>&nbsp</tr>");return b+="<tr><td>"+P_NO[a]+"<td colspan=3>"+P_DESCR[a]+'<td style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;">'+P_PRICE[a]+'<td style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;">'+P_TOTAL[a]+"</tr>"}
function genCreateReceiptFooterNoSum(a,b,c,e){return genCreateReceiptFooter(a,b,c,"","","",e)}
function genCreateReceiptFooter(a,b,c,e,f,g,h){a="<tr><td colspan=6>&nbsp</tr><tr><td colspan=2>"+(P_MWST[b]+'%\t\t<td style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;">'+P_MWST[b]+'<td style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;">'+P_NETTO[b]+'<td style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;" colspan=2>'+P_BRUTTO[b]+"</tr>");for(var k=0;k<h.length;k++){var m=h[k];m=m.replace(",","-");
a+='<tr><td id="taxval'+m+'" colspan=2><td id="mwst'+m+'" style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;">'+e+'<td id="netto'+m+'" style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;">'+f+'<td id="brutto'+m+'" style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;" colspan=2>'+g+"</tr>"}a=a+"<tr><td colspan=6>&nbsp</tr><tr><td>\t&nbsp;\t<td colspan=3>"+(P_SUM[b]+'<td id="priceinreceipt2" style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;" colspan=2>'+
g+"</td></tr>");a=a+'<tr><td colspan=6>&nbsp</tr><tr><td style="text-align:center;vertical-align:bottom;" colspan=6><center>&nbsp;<br>'+toHtmlInPaydesk(c).replace(/(?:\r\n|\r|\n)/g,"<br />");return a+"</center></tr>"}
function generateOneProdLine(a,b,c,e,f,g){var h=parseFloat(c).toFixed(2).replace(".",f);"A"!=e&&(b+=" ("+e+")");1==g&&(b="To-Go: "+b);e="<tr>";c=(a*c).toFixed(2).replace(".",f);0==a&&(c=h=a="");return e=e+('<td style="border: solid black 0px;padding: 3px;text-align:center;vertical-align:bottom;" id="count">'+a+'<td colspan=3 style="white-space: nowrap;overflow: hidden;text-overflow:ellipsis;width: 60%;">'+b)+'<td style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;">'+
h+('<td style="border: solid black 0px;padding: 3px;text-align:right;vertical-align:bottom;">'+c+"</tr>")}function generateProdPartByDbContent(a,b){var c;tablecontent="";for(c=0;c<b.length;c++){var e=b[c];tablecontent+=generateOneProdLine(e.count,e.productname,e.price,e.pricelevel,a)}return tablecontent}function listTaxes(a,b){for(var c=[],e=0;e<a.length;e++){var f=parseFloat(String(a[e]));f=f.toFixed(2).replace(".",b);0>c.indexOf(f)&&(c[c.length]=f)}return c}
function listTaxesBasedOnUntenList(a){for(var b=[],c=0;c<prodsOnReceiptList.length;c++)b.push(prodsOnReceiptList[c].tax);return listTaxes(b,a)}
function calcSum(){for(var a=listTaxesBasedOnUntenList(decpoint),b=[],c=[],e=[],f=0;f<a.length;f++)b[f]=0,c[f]=0,e[f]=0;for(var g=0,h=0,k=0;k<prodsOnReceiptList.length;k++){var m=prodsOnReceiptList[k],l=parseFloat(m.price);m=m.tax;f=parseFloat(m);m=m.replace(".",decpoint);var p=l/(1+f/100),t=l-p,q=0;for(f=0;f<a.length;f++)a[f]==m&&(q=f);b[q]+=p;c[q]+=l;e[q]+=t;g+=p;h+=l}for(k=0;k<a.length;k++)f=a[k],l=f.replace(",","-"),$("#taxval"+l).html(f+"%"),$("#mwst"+l).html(e[k].toFixed(2).replace(".",decpoint)),
$("#netto"+l).html(b[k].toFixed(2).replace(".",decpoint)),$("#brutto"+l).html(c[k].toFixed(2).replace(".",decpoint));billbrutto=h;billnetto=g;$("#priceinreceipt").html(h.toFixed(2).replace(".",decpoint)+" "+currency);$("#priceinreceipt2").html(h.toFixed(2).replace(".",decpoint)+" "+currency);lastCalcBruttoSum=h}
function bindCashButton(){$("#cashbutton").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();$("#cashdlg").dialog({autoOpen:!1,modal:!0,height:520,width:500,buttons:{Abbrechen:function(){$(this).dialog("close")},"Einlegen/Entnehmen":function(){cashOperation()}}});$("#includeowncash").html(P_INCLUDE_OWN[lang]);$("#cashmoney").val("");$("#cashremark").val("");$("#cashdlg").dialog("open");doAjax("POST","php/contenthandler.php?module=bill&command=getCashOverviewOfUser",
null,insertCashValues,"Fehler Kassenaktion");$(".ui-dialog-buttonset .ui-button").css("font-weight","bold");$(".ui-dialog-buttonset .ui-button").css("color","black");$(".ui-dialog-buttonset .ui-button:nth-child(2)").css("background-color","#e0e0d1");$(".ui-dialog-buttonset .ui-button:nth-child(2)").css("background-color","#ccff99");$(".ui-dialog-buttonset .ui-button:nth-child(3)").css("background-color","#ffcc99")})}
function insertCashValues(a){if("OK"!==a.status)$("#cashbyguests").html(""),$("#onlycashsum").html(""),$("#cashtotal").html(""),$(".currencyplaceholder").html(""),alert("Fehler bei Verbuchung einer Barein-/auslage: "+a.msg);else{var b=generateCashOverviewOfUser(a.cashperpayments);$("#cashbyguests").html(b);b=parseFloat(a.onlycash);$("#onlycashsum").html(b.toFixed(2).replace(".",decpoint));$("#cashtotal").html(parseFloat(a.total).toFixed(2).replace(".",decpoint));$(".currencyplaceholder").html(currency)}}
function cashOperation(){var a=$("#cashmoney").val().replace(",",".");if(isNaN(a))alert("Keine Zahl!");else{$("#cashdlg").dialog("close");var b=$("#cashremark").val(),c=$("#cashtype").val();checkForCashActionAndUserWill(c,a)?doAjax("POST","php/contenthandler.php?module=bill&command=doCashAction",{money:a,remark:b,cashtype:c},handleCashActionResult,"Fehler Kassenaktion"):alert("Abbruch")}}
function handleCashActionResult(a){"ERROR"===a.status?alert("Fehler "+a.msg):"OK"==a.status&&alert(P_CASHACTION_OK[lang])}function _findChepestPriceEntry(a){var b=Number.MAX_VALUE,c=null;a.forEach(function(e){var f=parseFloat(e.price);f<b&&(b=f,c=e)});return c}
function cancelAnArticle(a,b,c,e){var f=0-a.price;0!=a.unit&&(f=1*f/a.unitamount);a={id:a.id,name:a.longname,option:"",prodid:a.prodid,price:0-a.price,orderid:a.orderid,ordername:a.ordername,tax:a.tax,extras:[],changedPrice:f,togo:a.togo,unit:a.unit,unitamount:a.unitamount,phase:0,viewmode:b,isAlreadyOnReceipt:c};b="desktop"===b?_getTableId():$("#info-page").data("tid");doAjaxTransmitData("POST","php/contenthandler.php?module=queue&command=cancelinpaydesk",{tableid:b,prods:[a],print:0,payprinttype:"s",
paydeskstornocode:e},_manageAddedProd,"Fehler Produktbuchung",a)}function doCertainArticleStorno(a,b,c,e){var f=null;let g=[],h=!1;"onreceipt"===c?(g=prodsOnReceiptList,h=!0):g=prodsToPayList;g.forEach(function(k){k.id==a&&(f=k)});null!==f?cancelAnArticle(f,b,h,e):alert("ID Not found ")}
function bindMinusCheapestButton(a){$("#minuscheapest").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();cheaptestAlreadySubtracted?alert("Billigstes Produkt wurde bereits in Negation hinzugef\u00fcgt"):(b=_findChepestPriceEntry(prodsOnReceiptList),null!==b&&cancelAnArticle(b,a,!0,""))})}
function _manageAddedProd(a,b){if("OK"===a.status){stornoDoneAlready=!0;showStornoButtons=!1;$(".stornoarticleswitchon").hide();$(".stornoarticle").hide();let c=b.viewmode,e=b.isAlreadyOnReceipt;if("mobile"!==c||e)if("mobile"===c&&e)listToAddProductTo=prodsOnReceiptList;else if("desktop"===c&&e)listToAddProductTo=prodsToPayList;else return;else listToAddProductTo=prodsToPayList;_manageAddedProdCore(a,b,listToAddProductTo)}else alert("Fehler: "+a.msg)}
function _manageAddedProdCore(a,b,c){var e=b.viewmode;a={count:1,extras:[],id:a.queueids[0],longname:b.name,orderid:b.orderid,ordername:b.ordername,price:b.price,privelevelname:"A",printjobid:0,prodid:b.prodid,prodimageid:0,tax:b.tax,togo:b.togo,pricelevelname:"A"};c[c.length]=a;"mobile"===e&&(displayProdsOnReceipt(),displayProdsToPayForTable(),$("#minuscheapest").hide());"desktop"===e&&(aProdToPayIsClicked(a),displayProdsToPayForTable(),displayProdsOnReceipt());cheaptestAlreadySubtracted=!0}
function bindHostButton(a){if(1==showhostprint)$("#hostbutton").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();showHostTemplate=showHostTemplate?!1:!0;null!=a&&($(a).removeClass("ui-icon-check"),$(a).removeClass("ui-icon-delete"),$(a).removeClass("btnswitchoff"),$(a).removeClass("btnswitchon"),showHostTemplate?($(a).addClass("ui-icon-check"),$(a).addClass("btnswitchon")):($(a).addClass("ui-icon-delete"),$(a).addClass("btnswitchoff")));0==$("#info-page").data("billlanguage")?
createAllEntriesInReceipt():0==lang?alert("Bewirtungsbeleg steht nur f\u00fcr deutsche Kassenbons zur Verf\u00fcgung."):1==lang?alert("Bewirtungsbeleg is only possible for German receipts."):2==lang&&alert("Bewirtungsbeleg se puedo usar solo para tiques alemanes.")})}function printBill(a){doAjax("POST","php/contenthandler.php?module=printqueue&command=queueReceiptPrintJob",{billid:a,useaddrecprinter:1},null,"Druckfehler")}
function generateGuestResult(a,b,c){$("#hotelroomfoundguest").html("");a=a.trim().toLowerCase();if(""===a)$("#hotelroomselection").html("");else{var e="",f=!1,g=0,h="",k=guests;c==PAYMENT_GUEST&&(k=internalguests);$.each(k,function(m,l){var p=l.object.toString();l=l.guest;var t=0<=p.toLowerCase().indexOf(a),q=0<=l.toLowerCase().indexOf(a);if(t||q)g++,h=toHtmlInPaydesk(p+" - "+l),f?e+='<option value="'+m+'" >'+toHtmlInPaydesk(p+" - "+l)+"</option>":(f=!0,e+='<option value="'+m+'" selected>'+toHtmlInPaydesk(p+
" - "+l)+"</option>")});1===g&&$("#hotelroomfoundguest").html(h);$("#hotelroomselection").html(e)}b&&$("#hotelroomselection").selectmenu("refresh")}function generateCashOverviewOfUser(a){for(var b="",c=0;c<a.length;c++){var e=a[c];b+=e.payment+": <b>"+parseFloat(e.value).toFixed(2).replace(".",decpoint)+"</b> "+currency+"<br>"}return b}
function fillProdByPrintJobsList(a){prodsByPrintjob=[];for(var b=a.length,c=0;c<b;c++){var e=a[c],f=e.printjobid;0!=f&&(f in prodsByPrintjob?(f=prodsByPrintjob[f],f[f.length]=e):prodsByPrintjob[f]=[e])}}function fillProdByOrders(a){prodsByOrder=[];a.forEach(function(b){var c=b.orderid;c in prodsByOrder?(c=prodsByOrder[c],c[c.length]=b):prodsByOrder[c]=[b]})}
function setCalcModusBtn(){calcmodus==CALC_TOTAL?($("#payway").html(P_CHANGE_CALC[lang]),$("#calculatorarea").show(),$("#totalpricearea").hide(),$("#calcmodus").html("-&gt; "+CALC_TIP_TXT[lang]),$("#tiptxt").html(P_TOTAL_INCL_TIP[lang])):calcmodus==CALC_TIP?($("#payway").html(P_CHANGE_CALC[lang]),$("#calculatorarea").show(),$("#totalpricearea").hide(),$("#calcmodus").html("-&gt; "+CALC_TOTAL_TXT[lang]),$("#tiptxt").html(P_TIP[lang])):($("#payway").html(P_TOTALSUM[lang]),$("#totalpricearea").show(),
$("#calculatorarea").hide())}function fillValuesInCalc(a,b,c){$("#topayval").html(a);$("#totalpricearea").html(a);$("#haspaid").attr("placeholder",a);$("#haspaid").val("");$("#topayback").html("0"+b+"00");$("#tipfield").attr("placeholder","0.00".replace(".",b)+" "+c);$("#tipfield").val("")}function bindCalcReturn(){$("#calcreturnbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();calcChangeMoney()})}
function checkForCashActionAndUserWill(a,b){var c=!0;7==a&&0<b?c=confirm("\u00dcblicherweise wird die Einnahme f\u00fcr Trinkgeld beim Kassieren registriert und die \u00dcbergabe an den Arbeitnehmer als Entnahme aus der \u00fcber diesen Dialog angezeigt. Bei einem positiven Betrag sagen Sie jedoch, dass Sie Trinkgeld f\u00fcr den Arbeitnehmer einlegen. Ist das gewollt?"):1==a&&0<b?c=confirm("Ein positiver Betrag sagt aus, dass Geld als Privateinlage in die Kasse eingelegt werden soll. Ist das gewollt?"):
1==a&&0>=b?c=confirm("Ein negativer Betrag sagt aus, dass Geld als Privatentnahme aus der Kasse entnommen werden soll. Ist das gewollt?"):3==a&&0<b?c=confirm("Normalerweise nutzt man den Geldtransit, um zu beschreiben, dass Geld aus der Kasse entnommen wird. Ein positiver Betrag sagt jedoch aus, dass Geld in die Kasse gelegt werden soll. Ist das gewollt?"):6==a&&0<b&&(c=confirm("Bei einer Auszahlung wird ein negativer Betrag erwartet, weil der Kasse Geld entnomen wird. Wird jedoch ein positiver Betrag angegeben, w\u00fcrden Sie das Gegenteil aufzeichnen. Ist das gewollt?"));
return c}
function calcChangeMoney(){try{var a=$("#haspaid").val().trim(),b=parseFloat(a.replace(decpoint,".")),c=$("#topayval").html(),e=parseFloat(c.replace(decpoint,".")),f=0;if(calcmodus==CALC_TIP){var g=$("#tipfield").val().trim();g=""===g?0:parseFloat(g.replace(decpoint,"."));f=b-(e+g)}else{var h=$("#tipfield").val().trim();""==h?""==a?f="NaN":(f=b-e,$("#tipfield").val(c)):(h=parseFloat(h.replace(decpoint,".")),f=b-h)}if($.isNumeric(parseFloat(f))){var k=f.toFixed(2).replace(".",decpoint);$("#topayback").html(k)}else $("#topayback").html("?")}catch(m){$("#topayback").html("?")}}
function valueWithoutCurrency(a){return a.split(" ")[0]}function checkAndCalcRightTip(a,b){a=$("#tipfield").val().trim().replace(a,".");a=valueWithoutCurrency(a);if(""!==a&&isNaN(a))return{status:"ERROR",msg:"Trinkgeldfeld muss eine Zahl sein"};var c=parseFloat(a);""!==a&&b==CALC_TOTAL&&(c-=lastCalcBruttoSum);""===a&&(c=null);return null!==a&&0>c?{status:"ERROR",msg:"Negative Trinkgelder k\u00f6nnen bei einer Abrechnung nicht angegeben werden."}:{status:"OK",value:c}};
   </script>
</head>

<style>


</style> 

<body>
  
<div id="alertoverlay" onclick="alertoff();" >
  <div id="alerttext"></div>
</div>

<div class="tableospage">
        <span id="waiterdesktopheader" class="header"><span id="desktopviewname">Kellneransicht</span> (<span id="panelmodetxt">Bestellung</span>) <img src="img/connection.png" class="connectionstatus" style="display:none;" /> <img src="img/printerstatus.png" class="printerstatus" style="display:none;" /> <img src="img/tsestatus.png" class="tsestatus" style="display:none;" /> <img src="img/tasksstatus.png" class="tasksstatus" style="display:none;" /></span>
</div>
	
	
	<?php
		if (file_exists("customer/mywaiterdesktop.txt")) {
			readfile("customer/mywaiterdesktop.txt");
		} else {
			readfile("waiterdesktopdefault.txt");
		}
    
	?>

 
  <div class="tablefooter">
	  <span id="loggedinuser"></span>
	  <span id="versioninfo"></span>
  </div>
</div>

      <div id="selectiondialog" title="Auswahl" style="display:none;">Extras to select...</div>
      
      <div id="hoteldialog" title="Auswahl" style='display:none;'>
	      <h3><span id="hotelroomtitle">Hotelzimmer / Gast wählen</span></h3>
			<p>
			<form>
				<div id='hotelroomfoundguest'></div><br>
				<div id='roomselectionarea'><select id='hotelroomselection' class='guestselectionlist'></select><br></div>
				<input id='roomguesttextfield' type="text" placeholder='Zimmer oder Gast' class='input100 inputwhite' /><br><br>
				<input id='paym_hotel' type='submit' value='Auf Zimmer schreiben' class='guestselectionbutton'/>
			</form>
      </div>
      
      <div id="unsentorderdlg" title="Achtung" style="display:none;" >
	  Die Bestellung wurde noch nicht abgeschlossen. Wollen Sie die Bestellung verwerfen?
      </div>
      
      <div id="mainmenudlg" title="Hauptmenü" style="display:none;">Hauptmenü</div>

      <div id="actmenudlg" title="Aktion auswählen" style="display:none;">
	  <header id="actprodinfo"><span id=actcountno>3x</span> <span id="actname">Warsteiner</span> (<span id="actpriceinfo">(1,00 Euro)</span>)</header>
	  <div id="actareaforproducts">
	  <div id="actcounttogo">
	      <div id="actminusbtn" class="actbtn">-1</div>
	      <div id="actplusbtn" class="actbtn">+1</div>
	      
	      
	      <div id="acttogobtn" class="actbtn"><img id="togoicon" src="img/ok.png" style="display:none;"/><img id="notogoicon" src="img/notavailable.png" style="display:none;"/> &nbsp; To-Go</div>
	  </div>
	  <div id="actnumberarea">
		<div class="actlabel">Anzahl:&nbsp;</div>
		<div>
		  <input id="actnumberentryfield" class="input100 inputwhite" type="number" placeholder="Anzahl" />
		</div>
	  </div>
	  <div id="actremark">
	      <div class="actlabel">Bemerkung:&nbsp;</div>
	      <div>
		  <input id="actremarkfield" class="input100 inputwhite" type="text" placeholder="Notiz" />
	      </div>
	  </div>
	  <div id="actdiscount">
	      <div id="actdiscount1btn" class="actbtn">-1</div>
	      <div id="actdiscount2btn" class="actbtn">-1</div>
	      <div id="actdiscount3btn" class="actbtn">-1</div>
	  </div>
	  <div id="actprice">
	      <div>Neuer Preis:&nbsp;</div>
	      <div>
		  <input id="actpricefield" class="input100 inputwhite" type="text" placeholder="Neuer Preis" />
	      </div>
	  </div>
	  </div> <!-- actareaforproducts -->
      </div>
      
      <div id="ordereditemdlg" title="Aktion" style="display:none;">
	  <div id="ordereditem-info"></div>
	  <div id="orderedcancelpanel">
	      <input id="cancelcode" class="input100 inputwhite" type="password" placeholder="Stornierungscode" />
	  </div>
	  <div id="ordereditemremove" class="actbtn">Entfernen</div>
	  <div id="ordereditemreorder" class="actbtn">Nachbestellen</div>
	  <div id="ordereditemcancel" class="actbtn">Abbrechen</div>
	  <div id="deleteallordereditems" class="actbtnlarge">ALLE entfernen</div>
      </div>
      
      <div id="moveItemdslg" title="Auswahl der Orderelemente" style="display:none;" >
	  <div>Welche Orderelemente sollen dem neuen Tisch zugewiesen werden?</div>
	  <div id="selectallnothing">
	      <input id="selectallnothing_txt" class="input100 inputblue" type="submit" />
	  </div>
	  <ul id="productsToMoveList" class="extraschoice"></ul>
      </div>
      
      <div id="cashdlg" title="Ein-/Auslage" style="display:none;">
	  <h3><span id="cashoverviewtxt">Übersicht Kellnerkasse</span></h3>
 
	  <p><span id="overviewdetails">Diese Übersicht enthält die Bewirtungseinnahme durch den Kellner seit der letzten Tageslosung sowie
		    als weiteren Wert den Kassenstand unter Berücksichtigung der eigenen Eingaben und Entnahmen.</span><p>
	  <p><br><i><span id="cashsum">Bewirtungseinnahmen:</span></i>
	  <div style="padding-left: 50px;padding-right: 50px;">
		<span id=cashbyguests></span></p>
	  </div>
	  <div>
		<br><i>Barein-/auslagen:</i> <b><span id=onlycashsum></span></b> <span class="currencyplaceholder"></span><p>
		<br><i><span id="includeowncash">inkl. eigener Kassenein-/Auslagen:</span></i> <b><span id=cashtotal></span></b> <span class="currencyplaceholder"></span><p>
	  </div><br>
	  <p><div>
	      <input id="cashmoney" class="input100 inputblue" type="text" placeholder="0,00"/>
	  </div>
	  <div>
	      <input id="cashremark" class="input100 inputblue" type="text" placeholder="Bemerkung"/>
	  </div>
	  <div>
		  <select id="cashtype" style="width:100%;background-color: white; color:black;height:50px;">
			<option value="1">Privateinlage-/entnahme</option>
			<option value="3">Geldtransit</option>
			<!--<option value="4">Lohnzahlung</option> -->
			<option value="6">Auszahlung</option>
			<option value="7">Trinkgeld an Arb.nehmer</option><!--
			<option value="8">Trinkgeld an Arb.geber</option>-->
		  </select>
	  </div>
      </div>
      
      <div id="gencommentsdlg" title="Vordefinierte Kommentare" style="display:none;">
	  <input id="generalcommentfield" class="input100" placeholder="Kommentar" />

	  <ul id="commentschoice" class="extraschoice"></ul>

      </div>
      
      <div id="enterpricedlg" title="Benutzereingabe" style="display:none;">
	      <span id="entervalueunit">Eingabe...</span>
	      <div id="dlgpricearea">
                        <!-- enterpricefield must be of type text to allow comma values -->
		      <input id="enterpricefield" class="input100" type="text"/><br><br>

		      <table class=numfield id="numfield_num">
			      <tr><td>7<td>8<td>9</tr>
			      <tr><td>4<td>5<td>6</tr>
			      <tr><td>1<td>2<td>3</tr>
			      <tr><td>0<td colspan="2">,</tr>
			      <tr><td colspan="3" class="keyboardapply">Anwenden</tr>
		      </table>
	      </div>
	      <div id="dlgvoucherarea">
		      <p />
		      <table class=numfield id="numfield_num">
			      <tr><td><input id="entervoucherid" class="input100" type="text" placeholder="Gutscheinnr." /></tr>
			      <tr><td class="applyvoucherid"><a id="applyvoucherid" href="#" data-role="button" data-theme="c" >Anwenden</a></tr>
		      </table>
		     
	      </div>
      </div>
      
      <div id="recordsdlg" title="Tischprotokoll" style="display:none;">

      </div>
	      
</body>
</html>