function OsDatePicker(){this.EARLY_DATE=["Der gew\u00e4hlte Tag liegt in der Vergangenheit. Soll dieser dennoch ausgew\u00e4hlt werden?","The chosen date is in the past. Shall this date be take though?","El d\u00eda seleccionado pertenece al pasado. \u00bfDeber\u00eda seguir siendo seleccionado?"];this.isMonthViewVisible=!1;this.datemonthelem=this.datefieldelem=null;this.lang=0;this.blockedDays={};this.changeCallbackFct=this.currentYear=this.currentMonth=this.currentDay=null;this.init=function(a,
b,d,g,e,k,f,c){this.datefieldelem=a;this.datemonthelem=b;this.lang=d;this.blockedDays=this.createHashmapOfBlockedDays(c);this.changeCallbackFct=f;this.currentDay=g;this.currentMonth=e;this.currentYear=k;this.bindClickInDateTextField();this.displayDateInField()};this.getDate=function(){return new Date(this.currentYear,this.currentMonth,this.currentDay)};this.setDate=function(a){this.currentDay=a.getDate();this.currentMonth=a.getMonth();this.currentYear=a.getFullYear();this.off();this.displayDateInField()};
this.bindClickInDateTextField=function(){var a=this;$(this.datefieldelem).off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();a.toggle()});$(this.datefieldelem).off("keydown").on("keydown",function(b){b.stopImmediatePropagation();b.preventDefault()});$(this.datefieldelem).off("keypress").on("keypress",function(b){b.stopImmediatePropagation();b.preventDefault()});$(this.datefieldelem).off("keyup").on("keyup",function(b){b.stopImmediatePropagation();b.preventDefault()})};
this.createHashmapOfBlockedDays=function(a){var b={};a.forEach(function(d){b[d.scheduledate]=d.remark});return b};this.isBlockedDay=function(a,b,d){return this.isBlockedDayWithRemark(a,b,d).blocked};this.isBlockedDayWithRemark=function(a,b,d){a=pad(parseInt(a),2);b=pad(parseInt(b)+1,2);a=d+"-"+b+"-"+a;return a in this.blockedDays?{blocked:!0,remark:this.blockedDays[a]}:{blocked:!1,remark:""}};this.isTodayBlocked=function(){var a=new Date;return this.isBlockedDay(a.getDate(),a.getMonth(),a.getFullYear())};
this.isTodayBlockedWithRemark=function(){var a=new Date;return this.isBlockedDayWithRemark(a.getDate(),a.getMonth(),a.getFullYear())};this.blockDayInHashmap=function(a,b,d,g){a=pad(parseInt(a),2);b=pad(parseInt(b)+1,2);this.blockedDays[d+"-"+b+"-"+a]=g};this.releaseDayInHashmap=function(a,b,d){a=pad(parseInt(a),2);b=pad(parseInt(b)+1,2);delete this.blockedDays[d+"-"+b+"-"+a]};this.generateMonthView=function(){var a="<table class='viewdatemonthtable'>"+this.getTableHeader(this.currentMonth,this.currentYear);
a+="<tr class='center'><td>Mo<td>Di<td>Mi<td>Do<td>Fr<td>Sa<td>So</tr>";var b=new Date,d=b.getDate(),g=b.getMonth();b=b.getFullYear();var e=new Date(this.currentYear,this.currentMonth,1),k=(new Date(this.currentYear,this.currentMonth+1,0)).getDate(),f=this.getPreviousMonth(),c=(new Date(f.year,f.month+1,0)).getDate(),n=this.getNextMonth();e=e.getDay();0==e?e=6:e--;var p=e;a+="<tr class='center'>";c=c-p+1;for(var m=0;m<p;m++){var l=this.datemonthelem+"_"+c+"_"+f.month+"_"+f.year,h="";this.isBlockedDay(c,
f.month,f.year)&&(h=" blocked ");a+="<td id='"+l+"' class='selectableday othermonth "+h+"'>"+c;c++}for(c=1;c<=k;c++)l=this.datemonthelem+"_"+c+"_"+this.currentMonth+"_"+this.currentYear,h="",this.isBlockedDay(c,this.currentMonth,this.currentYear)&&(h=" blocked "),a=c==d&&this.currentMonth==g&&this.currentYear==b?a+("<td id='"+l+"' class='selectableday today "+h+"'>"+c):a+("<td id='"+l+"' class='selectableday thismonth "+h+"'>"+c),e++,6<e&&c<k&&(a+="</tr><tr class='center'>",e=0);c=1;for(m=e;7>m;m++)h=
"",this.isBlockedDay(c,n.month,n.year)&&(h=" blocked "),l=this.datemonthelem+"_"+c+"_"+n.month+"_"+n.year,a+="<td id='"+l+"' class='selectableday othermonth "+h+"'>"+c,c++;return a+"</tr></table>"};this.updateMonth=function(){var a=this.generateMonthView();$(this.datemonthelem).html(a);this.bindMonthSelector();this.bindDaySelector()};this.on=function(){this.updateMonth();$(this.datemonthelem).show();this.isMonthViewVisible=!0;this.bindMonthSelector()};this.off=function(){$(this.datemonthelem).hide();
this.isMonthViewVisible=!1};this.toggle=function(){if(this.isMonthViewVisible)this.off();else this.on()};this.getMonthName=function(a){return[["Jan","Jan","Ene"],["Feb","Feb","Feb"],["M\u00e4r","Mar","Mar"],["Apr","Apr","Abr"],["Mai","May","May"],["Jun","Jun","Jun"],["Jul","Jul","Jul"],["Aug","Aug","Ago"],["Sep","Sep","Sep"],["Okt","Oct","Oct"],["Nov","Nov","Nov"],["Dez","Dec","Dic"]][a][this.lang]};this.getTableHeader=function(a,b){return"<tr class='center dateselection'><td colspan='2' class='monthdec'>&lt;&lt;<td colspan='3'>"+
this.getMonthName(a)+" "+b+"<td colspan='2' class='monthinc'>&gt;&gt;</tr>"};this.displayDateInField=function(){var a=this.currentDay+"."+(this.currentMonth+1)+"."+this.currentYear;$(this.datefieldelem).val(a)};this.getPreviousMonth=function(){var a=this.currentMonth,b=this.currentYear;0==a?(b--,a=11):a--;return{month:a,year:b}};this.getNextMonth=function(){var a=this.currentMonth,b=this.currentYear;11==a?(b++,a=0):a++;return{month:a,year:b}};this.bindMonthSelector=function(){var a=this;$(this.datemonthelem+
" .monthdec").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();b=a.getPreviousMonth();a.currentMonth=b.month;a.currentYear=b.year;a.updateMonth()});$(this.datemonthelem+" .monthinc").off("click").on("click",function(b){b.stopImmediatePropagation();b.preventDefault();b=a.getNextMonth();a.currentMonth=b.month;a.currentYear=b.year;a.updateMonth()})};this.bindDaySelector=function(){var a=this;$(this.datemonthelem+" .selectableday").off("click").on("click",function(b){b.stopImmediatePropagation();
b.preventDefault();var d=this.id.split("_");b=parseInt(d[1]);var g=parseInt(d[2]),e=parseInt(d[3]),k=!0;d=new Date(e,g,b);var f=new Date;f.setHours(0,0,0,0);f>d&&0==confirm(a.EARLY_DATE[a.lang])&&(k=!1);k&&(a.currentDay=b,a.currentMonth=g,a.currentYear=e,a.displayDateInField(),null!=a.changeCallbackFct&&(b=a.isBlockedDayWithRemark(b,g,e),a.changeCallbackFct(d,b.blocked,b.remark)));a.toggle()})}};
