var MAN_CLS_COINS_NOTES_FIELDS_NOT_CORRECTLY_FILLED=["Entweder m\u00fcssen alle oder gar kein Feld des Z\u00e4hlprotokolls korrekt ausgef\u00fcllt sein.","Either all or no fields of the counting protocol must be filled in correctly.","Todos o ninguno de los campos del protocolo de conteo deben ser llenados."],MAN_COUNTING_SUM=["Summe","Sum","Total"],MAN_NO_COUNTING_DONE=["Z\u00e4hlprotokoll wurde nicht erfasst.","No counting protocol available.","No hay ningun protocolo de conteo."],MAN_NOTES_VALUE=
["Wert","Value","Valor"],MAN_COIN_NOTE_TYPE=["Typ","Type","Typo"],MAN_COIN_NOTE_SUM=["Summe","Sum","Total"],MAN_COIN_NOTE_COUNT=["Anzahl","Number","Numero"];
function Closing(e,l,q){this.closingListExpanded=!1;this.hint=this.notesHeader=this.coinsHeader=this.areaHeader="";this.l=l;this.coins=[];this.notes=[];this.decpoint=e;this.currency=q;this.bindNewClosingExpand=function(a,c,d,b){var f=this;this.areaHeader=a;this.coinsHeader=c;this.notesHeader=d;this.hint=b;$("#closinglist").off("collapsibleexpand").on("collapsibleexpand",function(g){g.stopImmediatePropagation();g.preventDefault();f.closingListExpanded||(f.closingListExpanded=!0,f._createGui())})};
this._createGui=function(){doAjax("GET","php/contenthandler.php?module=admin&command=getcoinsandnotes",null,this._handleCoinsAndNotesAndCreateGui.bind(this),"Fehler M\u00fcnzen/Banknoten",!0);this.updateXBelegArea()};this.updateXBelegArea=function(){doAjax("GET","php/contenthandler.php?module=closing&command=getxbeleg",null,this._insertXBeleg.bind(this),"Fehler Tageserfassung-Vorabwerte Benutzer",!0)};this._insertXBeleg=function(a){if("OK"!==a.status)console.log(a.msg);else{var c=this._createSubPartUserSums(a.msg.usersums,
"xbeleg");c+=this._createSubPartTaxesSums(a.msg.taxes,"xbeleg");c+=this._createSalesAndTipsByPaymentAndTax(a.msg.payments,"xbeleg");c+=this._createBonstornoTable(a.msg.cancelledbills,e,"xbeleg");c+=this._createCancelledOrdersTable(a.msg.cancelledorders,e,"xbeleg");""===c&&(c="Keine Eintr\u00e4ge");$("#xbeleg").html(c)}};this._insertXBelegTaxes=function(a){"OK"!==a.status?console.log(a.msg):(a=this._createSubPartTaxesSums(a.msg,"xbeleg"),""===a&&(a="Keine Daten"),$("#xbelegtaxes").html(a))};this._insertUserGroupedSumOfXBeleg=
function(a){"OK"!==a.status?console.log(a.msg):(a=this._createSubPartUserSums(a.msg,"xbeleg"),""===a&&(a="Keine Daten"),$("#xbelegusersums").html(a))};this._handleCoinsAndNotesAndCreateGui=function(a){var c='<p /><span class="areaheader">'+this.areaHeader+"</span>";if("OK"===a.status){this.coins=a.msg.coins;this.notes=a.msg.notes;var d=a.msg.notevalname;c+="<p />"+this._createGuiCore(this.coins,this.coinsHeader,a.msg.coinvalname,"c");c+=this._createGuiCore(this.notes,this.notesHeader,d,"n")}c+='<p /><span class="coinsnotesheader">'+
MAN_COUNTING_SUM[lang]+"</span><br>";c=c+('<input id="countingsum" value="" type="text" readonly /> '+d)+('<p /><div class="hint">'+this.hint+"</div>");$("#countingprotocol").html(c);this._bindCountingChange()};this._bindCountingChange=function(){var a=this;$(".countingfield").off("keyup").on("keyup",function(c){a._calcSum()})};this._calcSum=function(){var a=0;this.coins.forEach(function(d,b){b=$("#coinnote_c_"+d).val().trim();""!==b&&(b=parseInt(b),isInt(b)?a+=b*d:$("#countingsum").val("?"))});this.notes.forEach(function(d,
b){b=$("#coinnote_n_"+d).val().trim();""!==b&&(b=parseInt(b),isInt(b)?a+=100*b*d:$("#countingsum").val("?"))});var c=(a/100).toFixed(2).replace(".",this.decpoint);$("#countingsum").val(c)};this._createGuiCore=function(a,c,d,b){var f='<p /><span class="coinsnotesheader">'+c+"</span><br>";a.forEach(function(g,m){f+='<input id="coinnote_'+b+"_"+g+'" type="number" min="0" class="countingfield" />';f+=" * "+g+" "+d+"<br>"});return f};this.checkCoinsNotesValues=function(){var a=this._checkCoinNoteFieldsAreFilled("c",
this.coins),c=this._checkCoinNoteFieldsAreFilled("n",this.notes),d=a.filled+c.filled;a=a.unfilled+c.unfilled;c=this._getCounted();return 0<d&&0<a?{status:!1,msg:MAN_CLS_COINS_NOTES_FIELDS_NOT_CORRECTLY_FILLED[this.l]}:0<d?(coinscount=this._getCountOfCoinNoteFields("c",this.coins),notescount=this._getCountOfCoinNoteFields("n",this.notes),{status:!0,msg:"OK",counting:1,coinscount,notescount,counted:c}):{status:!0,msg:"OK",counting:0}};this._checkCoinNoteFieldsAreFilled=function(a,c){var d=0,b=0;c.forEach(function(f,
g){""==$("#coinnote_"+a+"_"+f).val().trim()?b++:d++});return{filled:d,unfilled:b}};this._getCountOfCoinNoteFields=function(a,c){var d=[];c.forEach(function(b,f){f=$("#coinnote_"+a+"_"+b).val().trim();d[d.length]={value:b,count:f}});return d};this.clearCountingFields=function(){this.coins.forEach(function(a,c){$("#coinnote_c_"+a).val("")});this.notes.forEach(function(a,c){$("#coinnote_n_"+a).val("")});$("#countingsum").val("")};this._getCounted=function(){this._calcSum();var a=$("#countingsum").val();
return void 0===a||""===a?0:a.replace(",",".")};this._createSubPartCategorySums=function(a){var c="";if(0<a.length){c=c+'<br><table class="categorysums clostable"><tr><th>'+(MAN_CATEGORY[lang]+"<th>"+MAN_BILLSUMALL[lang]+" ("+this.currency+")</tr>");for(var d=0;d<a.length;d++){var b=a[d];if(0==b.kind)c+="<tr><td>"+toHtml(cat1name);else if(1==b.kind)c+="<tr><td>"+toHtml(cat2name);else continue;c+="<td>"+b.brutto.replace(".",this.decpoint);c+="</tr>"}c+="</table><br>"}return c};this._createSalesAndTipsByPaymentAndTax=
function(a,c){var d=$("#admin-page").data("decpoint"),b="";0<a.length&&(b+='<table class="'+c+'paymenttaxsums clostable">',b+="<tr><th colspan='5'><i>Ums\u00e4tze und Trinkgelder</i></th></tr>",b+="<tr><th>Zahlweg<th>Steuersatz<th>Brutto<th>Netto<th>Steuer</tr>",a.forEach(function(f){b+="<tr><td>"+f.payment;b+="<td>"+f.tax.toString().replace(".",d);b+="<td>"+f.brutto.toString().replace(".",d);b+="<td>"+f.netto.toString().replace(".",d);b+="<td>"+f.mwst.toString().replace(".",d);b+="</tr>"}),b+="</table><br>");
return b};this._formatToTwoDigits=function(a){return"string"===typeof a?parseFloat(a).toFixed(2):a.toFixed(2)};this._createSubPartUserSums=function(a,c){var d="";if(0<a.length){var b=0,f=0,g=0,m=0,k=0,n=0;d=d+('<table class="'+c+'usersums clostable"><tr><th>')+(MAN_USERNAME[lang]+"<th>Ums\u00e4tze (Bar)<th>Ums\u00e4tze (Unbar)<th>Barein-/Auslagen<th>Geldtransit<th>Trinkgeld<th>Summe</tr>");for(c=0;c<a.length;c++){var h=a[c];d+="<tr><td>"+h.username;d+="<td>"+this._formatToTwoDigits(h.salesinbar).toString().replace(".",
this.decpoint);d+="<td><i>EC:"+this._formatToTwoDigits(h.salesinec).toString().replace(".",this.decpoint)+"</i>";d+="<br><i>Kreditk.:"+this._formatToTwoDigits(h.salesincredit).toString().replace(".",this.decpoint)+"</i>";d+="<br>Summe:"+this._formatToTwoDigits(h.salesnotinbar).toString().replace(".",this.decpoint);d+="<td>"+this._formatToTwoDigits(h.sumcash).toString().replace(".",this.decpoint);d+="<td>"+this._formatToTwoDigits(h.geldtransit).toString().replace(".",this.decpoint);d+="<td>"+this._formatToTwoDigits(h.sumtips).toString().replace(".",
this.decpoint);var p=h.billsumall;"number"===typeof h.billsumall&&(p=h.billsumall.toFixed(2));d+="<td>"+p.replace(".",this.decpoint);b+=parseFloat(h.salesinbar);f+=parseFloat(h.salesnotinbar);g+=parseFloat(h.sumcash);m+=parseFloat(h.geldtransit);n+=parseFloat(h.sumtips);k+=parseFloat(h.billsumall)}d+="<tr><td>Summe<td>"+b.toFixed(2).replace(".",this.decpoint)+"<td>"+f.toFixed(2).replace(".",this.decpoint)+"<td>"+g.toFixed(2).replace(".",this.decpoint)+"<td>"+m.toFixed(2).replace(".",this.decpoint)+
"<td>"+n.toFixed(2).replace(".",this.decpoint)+"<td>"+k.toFixed(2).replace(".",this.decpoint)+"</tr>";d+="</table><br>"}return d};this._createTipsPart=function(a){var c=this,d='<table class="tips clostable">';d+="<tr><th>"+MAN_USERNAME[lang]+"<th>Trinkgeld</tr>";0===a.length?d+="<tr><td colspan=2>Keine Eintr\u00e4ge</tr>":a.forEach(function(b){null!==b.sum&&(d+="<tr>",d+="<td>"+toHtml(b.iter).replace(".",c.decpoint),d+="<td>"+b.sum.replace(".",c.decpoint),d+="</tr>")});return d+="</table>"};this._createSubPartTaxesSums=
function(a,c){var d="",b=a.salesandtips,f=a.casheswithouttransit;a=a.transits;if(0===b.length&&0===f.length&&0===a.length)return d;d=d+('<br><table class="'+c+'taxessums clostable"><tr><th>Typ<th>')+(MAN_TAX[lang]+"<th>"+MAN_BILLSUMNETTO[lang]+" ("+this.currency+")<th>"+MAN_BILLSUMALL[lang]+" ("+this.currency+")</tr>");if(0<b.length){var g=0,m=0;for(c=0;c<b.length;c++){var k=b[c];d+="<tr>";if("VERKAUF"===k.thetype)d+="<td>Verkauf";else if("TRINKG."===k.thetype)d+="<td>Trinkgeld";else if("C"===k.thetype||
"CT"===k.thetype)continue;else d+="<td>?";d+="<td>"+k.tax.replace(".",this.decpoint);d+="<td>"+k.netto.replace(".",this.decpoint);d+="<td>"+k.brutto.replace(".",this.decpoint);d+="</tr>";g+=parseFloat(k.netto);m+=parseFloat(k.brutto)}d+="<tr><td>Summen (alle Steuers\u00e4tze)<td>&nbsp;<td>"+g.toFixed(2).replace(".",this.decpoint)+"<td><b>"+m.toFixed(2).replace(".",this.decpoint)+"</b></tr>"}if(0<f.length)for(c=0;c<f.length;c++)k=f[c],d+="<tr>",d+="<td>Einlage/Auslage (Bar)",d+="<td>"+k.tax.replace(".",
this.decpoint),d+="<td>"+k.netto.replace(".",this.decpoint),d+="<td>"+k.brutto.replace(".",this.decpoint);if(0<a.length)for(c=0;c<a.length;c++)b=a[c],d+="<tr>",d+="<td>Geldtransit (Bar)",d+="<td>"+b.tax.replace(".",this.decpoint),d+="<td>"+b.netto.replace(".",this.decpoint),d+="<td>"+b.brutto.replace(".",this.decpoint);return d+"</table><br>"};this._createSubPartCountingProtocol=function(a,c,d){var b="<br>"+MAN_COUNTING_PROTOCOL[lang]+": ";if(0<a.length){b=b+'<br><table class="countingsums clostable"><tr><th>'+
(MAN_COIN_NOTE_COUNT[lang]+"<th>"+MAN_NOTES_VALUE[lang]+"<th>"+MAN_COIN_NOTE_SUM[lang]+" ("+this.currency+")<th>"+MAN_COIN_NOTE_TYPE[lang]+"</tr>");for(var f=0,g=0;g<a.length;g++){var m=a[g],k=m.count,n=m.sum,h=MAN_COINS[lang],p=c;0==m.iscoin&&(h=MAN_NOTES[lang],p=d);f+=parseFloat(n);n=n.replace(".",this.decpoint);b+="<tr><td>"+k+"<td>"+m.value+" "+p+"<td>"+n+"<td>"+h+"</tr>"}a=f.toFixed(2).replace(".",this.decpoint);b+='<tr><td colspan="4">'+MAN_COIN_NOTE_SUM[lang]+": "+a+" "+this.currency+"</tr>";
b+="</table><br>"}else b+=MAN_NO_COUNTING_DONE[lang];return b};this._createBonstornoTable=function(a,c,d){var b="<p /><table class='"+d+"cancelledbills clostable'>";b+="<tr><th colspan='6'>Kassenbonstornos (Trinkg.-Stornos nicht enthalten)</th></tr>";b+="<tr><th>Datum Ausstellung<th>Bon-ID<th>Datum Stornierung<th>Bon-ID Stornierung<th>Betrag<th>Stornogrund</tr>";if(0===a.length){if("xbeleg"===d)return"";b+="<tr><td colspan='6'>Keine Eintr\u00e4ge</tr>"}else a.forEach(function(f){b+="<tr>";b+="<td>"+
f.origdate;b+="<td>"+f.billuid;b+="<td>"+f.canceldate;b+="<td>"+f.cancellingbilluid;b+="<td>"+f.brutto.replace(".",c);b+="<td>"+f.reason;b+="</tr>"});return b+="</table>"};this._createCancelledOrdersTable=function(a,c,d){var b="<p /><table class='"+d+"cancelledorders clostable'>";b+="<tr><th colspan='6'>Bestellstorno</th></tr>";b+="<tr><th>Artikel<th>Tisch<th>Bestellzeitpunkt<th>Preis</tr>";if(0===a.length){if("xbeleg"===d)return"";b+="<tr><td colspan='6'>Keine Eintr\u00e4ge</tr>"}else a.forEach(function(f){b+=
"<tr>";b+="<td>"+f.articlename;b+="<td>"+f.tablename;b+="<td>"+f.ordertime;b+="<td>"+f.price.replace(".",c);b+="</tr>"});return b+="</table>"};this._createClosingPartOnlyFrame=function(a,c){c=c.id;a='<div id="clospart_'+c+'" + data-role="collapsible" data-theme="e" data-content-theme="e" class="closarea"><h3>'+(toHtml(a)+"</h3>");return a=a+"<p /><div id='closcontent_"+(c+"'>Abfrage nicht m\u00f6glich oder Benutzer hat nicht die erforderlichen Rechte</div></p></div>")};this._bindClosArea=function(){var a=
this;$(".closarea").off("collapsibleexpand").on("collapsibleexpand",function(c){c.stopImmediatePropagation();c.preventDefault();c={id:this.id.split("_")[1]};doAjax("GET","php/contenthandler.php?module=closing&command=getcertainclosing",c,a._insertInfoOfCertainClosing.bind(a),"Erfassungsdaten nicht abrufbar",!0)})};this._insertInfoOfCertainClosing=function(a){var c=a.closingid,d=$("#admin-page").data("decpoint"),b=a.barTotalBeforeTE,f=a.barTotalAfterTE,g=a.ordercancels;"number"!==typeof g&&(g=parseFloat(g));
g=g.toFixed(2);b="<p /><table class='closingsums clostable'><tr><td>Bargeld in Kasse vor TE<td id='cashinpaydeskbeforeclosing_"+(c+"'>"+b.replace(".",d)+"</tr>");b+="<tr><td>Bargeld in Kasse nach TE (errechnet)<td id='cashinpaydeskafterclosing_"+c+"'>"+f.replace(".",d)+"</tr>";0<a.countingprotocol.length&&(b+="<tr><td>Bargeld in Kasse nach TE (gez\u00e4hlt)<td>"+a.counted.replace(".",d)+"</tr>",b+="<tr><td>Bargelddifferenz<td>"+a.diffsollist.toFixed(2).replace(".",d)+"</tr>");b+="<tr><td>Bestellstornos<td id='ordercancels_"+
c+"'>"+g.replace(".",d)+"</tr>";b+="<tr><td>Umsatz<td id='puresales_"+c+"' class='puresales'>"+a.puresales.toFixed(2).replace(".",d)+"</tr>";b=b+"</table><p /><h3>\u00c4nderungen mit dieser Erfassung</h3>"+this._createSubPartUserSums(a.usersums,"");b+=this._createTipsPart(a.tips);b+=this._createSubPartTaxesSums(a.taxessums,"");b+=this._createSalesAndTipsByPaymentAndTax(a.salesandtipsbypaymentandtax,"");b+=this._createSubPartCategorySums(a.categorysums);b+=this._createSubPartCountingProtocol(a.countingprotocol,
a.coinname,a.notename);b+=this._createBonstornoTable(a.cancelledbills,d,"");b+=this._createCancelledOrdersTable(a.ordercancelsdetails,d,"");b+="<p>"+MAN_CLOSING_DET_TXT[lang]+"</p>";b=b+('<p id="closingbuttonsstart_'+c+'">  <button type="submit" data-theme="f" class="csvExportButton" data-icon="check" id="csvexport_')+(c+'">'+MAN_CSV_EXP_RECEIPTS[lang]+"</button>");b+='<button type="submit" data-theme="f" class="csvExportAllButton" data-icon="check" id="csvallexport_'+c+'">'+MAN_CSV_EXP_ALL[lang]+
"</button>";a=$("#receiveremail").val();b=b+('<fieldset class="ui-grid-a" id="emailfieldset'+c+'"><div class="ui-block-a"><input type="email" name="email_')+(c+'" id="email_'+c+'" value="'+a+'" class="whiteinput" /></div><div class="ui-block-b"><button type="submit" data-theme="c" class="csvEmailAllButton" data-icon="arrow-r" id="csvallemail_')+(c+'">'+MAN_EMAIL_DATA[lang]+"</button></div>");b+='<button type="submit" data-theme="f" class="printButton" data-icon="check" id="printexport_'+c+'">'+MAN_PRINT_ALL[lang]+
"</button>";b+='<button type="submit" data-theme="f" class="printsummary" data-icon="check" id="printsummary_'+c+'">'+MAN_PRINT_RECEIPT[lang]+"</button>";b+='<button type="submit" data-theme="f" class="closhtml" data-icon="check" id="closhtml_'+c+'">'+MAN_CLOS_HTML[lang]+"</button>";$("#closcontent_"+c).html(b);$("#closcontent_"+c).trigger("create");bindingClosing()};this.displayClosings=function(a){var c=this,d="";$.each(a,function(b,f){b=f.remark;var g=f.closdate+" ("+MAN_DAYNAMES_START_SUNDAY[f.dayofweek][lang]+
")";d=""!==b?d+c._createClosingPartOnlyFrame(f.id+": "+g+": "+b,f):d+c._createClosingPartOnlyFrame(f.id+": "+g,f)});$("#partofclosings").html(d);$("#partofclosings").trigger("create");this._bindClosArea()}}
function bindingClosing(){$("#createclosing").off("click").on("click",function(e){e=$("#remarkfield").val();$("#remarkfield").val("");e=e.replace(/\f/g,"").replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\v/g,"");startCreateClosing(e,!0)});$("#createclosingnoprint").off("click").on("click",function(e){e=$("#remarkfield").val();$("#remarkfield").val("");e=e.replace(/\f/g,"").replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\v/g,"");startCreateClosing(e,!1)});$(".csvExportButton").off("click").on("click",
function(e){e=this.id;var l=e.indexOf("_");e=e.substr(l+1,e.length-1);window.location.href="php/contenthandler.php?module=bill&command=exportCsvOfClosing&closingid="+e});$(".csvExportAllButton").off("click").on("click",function(e){e=this.id;var l=e.indexOf("_");e=e.substr(l+1,e.length-1);window.location.href="php/contenthandler.php?module=closing&command=exportCsv&closingid="+e});$(".csvExportGuestButton").off("click").on("click",function(e){e=this.id;var l=e.indexOf("_");e=e.substr(l+1,e.length-
1);window.location.href="php/contenthandler.php?module=closing&command=exportGuestCsv&closingid="+e});$(".csvEmailAllButton").off("click").on("click",function(e){e=this.id;var l=e.indexOf("_");e=e.substr(l+1,e.length-1);l=$("#email_"+e).val();""===l?alert(MAN_EMAIL_EMPTY[lang]):0>l.indexOf("@")?alert(MAN_EMAIL_WRONG_FORMAT[lang]):doAjax("GET","php/contenthandler.php?module=closing&command=emailCsv",{closingid:e,emailaddress:l,topic:MAN_CLOSING[lang]},handleResultOfDbAction,"Emailproblem")});$(".printButton").off("click").on("click",
function(e){e.stopImmediatePropagation();e.preventDefault();e=this.id;var l=e.indexOf("_");e=e.substr(l+1,e.length-1);doAjax("GET","php/contenthandler.php?module=closing&command=getClosing",{closingid:e},doPrinting,"Druckproblem")});$(".printsummary").off("click").on("click",function(e){e.stopImmediatePropagation();e.preventDefault();e=this.id.split("_")[1];2==generalVals[1]?doAjax("GET","php/contenthandler.php?module=printqueue&command=queueClosingSummary",{closingid:e},null,"Druckproblem"):doAjax("GET",
"php/contenthandler.php?module=closing&command=getClosingSummary",{closingid:e},doPrintClosingSummary,"Druckproblem")});$(".closhtml").off("click").on("click",function(e){e.stopImmediatePropagation();e.preventDefault();e=this.id.split("_")[1];window.open("php/contenthandler.php?module=closing&command=htmlreport&closid="+e,"_blank")});$("#select-year").change(function(){getClosingsOfSelectedDate()});$("#select-month").change(function(){getClosingsOfSelectedDate()})};
