var allgroups=[],customers=[],decpoint=".",currency="",payments=[],selGroupForAssigment=-1,cusbills={};
function getGeneralConfigItemsCus(){$("#customersearch").val("");$("#customersearchremark").val("");$("#groupsearch").val("");$("#grpAssignmentSelection").val("");clearNewCustomerFields();clearNewGroupFields();doAjax("GET","php/contenthandler.php?module=admin&command=getGeneralConfigItems",null,insertConfigDoRest,"Fehler Konfigurationsdaten");doAjax("GET","php/contenthandler.php?module=customers&command=getPaymentsForGuest",null,insertPayments,"Fehler Zahlungswege",!0);customizeDatePicker("#newcustomercheckin",
null);customizeDatePicker("#newcustomercheckout",null);customizeDatePicker("#customerdate","")}
function insertConfigDoRest(a){"OK"===a.status?(a=a.msg,$("#customersearch").val(""),$("#customersearchremark").val(""),$("#customersearchaddress").val(""),setLanguage(a.userlanguage),decpoint=a.decpoint,currency=a.currency,1==a.allowguestexport?($("#buttonsforguestexport").show(),bindGuestexportBtns()):$("#buttonsforguestexport").hide(),bindGroupsOrCustomerBtns(),showCustomersArea(),startSearch()):setTimeout(function(){document.location.href="index.html"},250)}
function insertPayments(a){if("OK"==a.status){a=a.msg;payments=[];for(var b=0;b<a.length;b++){var c=a[b];payments[payments.length]={id:c.id,name:c.name}}setPaymentsInAllGuestActions()}}function setPaymentsInAllGuestActions(){var a="<br><b>"+CUS_DECLARE_ALL_PAY[l]+"</b>:<br>";for(var b=0;b<payments.length;b++){var c=payments[b];a+=createApplyButton("paymentallguests_"+c.id,c.name,"e","paymentpayallguests")}$("#payalldiv").html(a);$("#payalldiv").trigger("create")}
function createPaymentsArea(a,b,c){c=createCollapsibleStartGeneral("paymentsarea_"+a,c,"f","paymentsarea",!0);for(var d=0;d<payments.length;d++){var e=payments[d];c+=createApplyButton("payment_"+a+"_"+e.id+"_"+b,e.name,"e","paymentpay")}return c+"</div>"}
function showCustomersArea(){$("#customersarea").show();$("#groupsarea").hide();$("#customersbtn").buttonMarkup({theme:"f"});$("#customersbtn").buttonMarkup({icon:"arrow-d"});$("#groupsbtn").buttonMarkup({theme:"c"});$("#groupsbtn").buttonMarkup({icon:"arrow-r"})}
function showGroupsArea(){$("#customersarea").hide();$("#groupsarea").show();$("#customersbtn").buttonMarkup({theme:"c"});$("#customersbtn").buttonMarkup({icon:"arrow-r"});$("#groupsbtn").buttonMarkup({theme:"f"});$("#groupsbtn").buttonMarkup({icon:"arrow-d"})}
function bindGroupsOrCustomerBtns(){$("#customersbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();showCustomersArea()});$("#groupsbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();showGroupsArea()});$("#newcustomerbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=$("#newcustomername").val().trim();var b=$("#newcustomeremail").val().trim(),c=$("#newcustomeraddress").val().trim(),
d=$("#newcustomerremark").val().trim(),e=$("#newcustomerphone").val().trim(),f=$("#newcustomermobil").val().trim(),g=$("#newcustomerwww").val().trim(),h=$("#newcustomerhello").val().trim(),k=$("#newcustomerregards").val().trim(),m=$("#newcustomerroom").val().trim(),p=0;$("#newcustomerpermanent").is(":checked")&&(p=1);if(""===a)alert(CUS_EMPTY_NAME[l]);else{var n=getCheckinouts("#newcustomercheckin","#newcustomercheckout");n.valid?(a={name:a,email:b,addr:c,remark:d,phone:e,mobil:f,www:g,hello:h,regards:k,
checkin:n.checkin,checkout:n.checkout,room:m,permanentguest:p},cusCheckTextLengths(a)&&doAjax("POST","php/contenthandler.php?module=customers&command=createNewCustomer",a,handleCreateCustomerResult,"Gast anlegen unm\u00f6glich",!0)):alert(CUS_CHECKIN_AFTER_OUT[l])}});$("#customersearch").off("keyup").on("keyup",function(a){startSearch()});$("#customersearchremark").off("keyup").on("keyup",function(a){startSearch()});$("#customersearchaddress").off("keyup").on("keyup",function(a){startSearch()});$("#groupsearch").off("keyup").on("keyup",
function(a){startSearch()});$("#newgroupbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=$("#newgroupname").val().trim();var b=$("#newgroupremark").val().trim();""===a?alert(GROUP_EMPTY_NAME[l]):doAjax("POST","php/contenthandler.php?module=customers&command=createNewGroup",{name:a,remark:b},handleCreateGroupResult,"Gruppe anlegen unm\u00f6glich",!0)});$("#customerlog").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();window.open("php/contenthandler.php?module=customers&command=exportLog",
"_blank")});$("#reportbills").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();window.open("php/contenthandler.php?module=customers&command=reportbills","_blank")})}
function bindOnDynamicCustomersBtn(){$(".applycustomer").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id.split("_")[1];for(var b=[],c=0;c<allgroups.length;c++){var d=allgroups[c];$("#grplistitem_"+a+"_"+d.id).hasClass("ingroup")&&(b[b.length]=d.id)}getCheckinouts("#cusfield_checkin_"+a,"#cusfield_checkout_"+a).valid?(0===b.length&&(b=""),c=0,$("#cusfield_permanentguest_"+a).is(":checked")&&(c=1),a={id:a,name:$("#cusfield_name_"+a).val().trim(),email:$("#cusfield_email_"+
a).val().trim(),addr:$("#cusfield_address_"+a).val().trim(),remark:$("#cusfield_remark_"+a).val().trim(),phone:$("#cusfield_phone_"+a).val().trim(),mobil:$("#cusfield_mobil_"+a).val().trim(),www:$("#cusfield_www_"+a).val().trim(),hello:$("#cusfield_hello_"+a).val().trim(),regards:$("#cusfield_regards_"+a).val().trim(),permanent:c,groups:b},cusCheckTextLengths(a)&&doAjax("POST","php/contenthandler.php?module=customers&command=changeCustomer",a,handleChangeCustomerResult,"Gast \u00e4ndern unm\u00f6glich",
!0)):alert(CUS_CHECKIN_AFTER_OUT[l])});$(".deletecustomer").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();var b=this.id.split("_")[1];areYouSureCus("Gast l\u00f6schen",CUS_DEL_TEXT[l],CUS_DEL[l],function(){deleteCustomerCore(b)})});$(".applygroup").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id.split("_")[1];a={id:a,name:$("#grpfield_name_"+a).val().trim(),remark:$("#grpfield_remark_"+a).val().trim()};doAjax("POST",
"php/contenthandler.php?module=customers&command=changeGroup",a,handleChangeGroupResult,"Gruppe \u00e4ndern unm\u00f6glich",!0)});$(".deletegroup").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();var b=this.id.split("_")[1];areYouSureCus("Gruppe l\u00f6schen",GRP_DEL_TEXT[l],GRP_DEL[l],function(){deleteGroupCore(b)})});$(".grpsel").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id.split("_")[1];var b=this.id.split("_")[2];
a="#grplistitem_"+a+"_"+b;$(a).hasClass("ingroup")?($(a).removeClass("ingroup"),$(a).addClass("notingroup"),$(a+" a").removeClass("ui-btn-f"),$(a+" a").addClass("ui-btn-c"),$(a+" a").removeClass("ui-icon-check"),$(a+" a").addClass("ui-icon-delete")):($(a).removeClass("notingroup"),$(a).addClass("ingroup"),$(a+" a").removeClass("ui-btn-c"),$(a+" a").addClass("ui-btn-f"),$(a+" a").removeClass("ui-icon-delete"),$(a+" a").addClass("ui-icon-check"))});$(".groupsendemail").off("click").on("click",function(a){a.stopImmediatePropagation();
a.preventDefault();a=this.id.split("_")[1];var b=$("#grpemailsubjectfield_grpemailsubject_"+a).val(),c=$("#grpemailbccfield_grpemailbcc_"+a).val(),d=$("#grpemailtextfield_grpemailtext_"+a).val();doAjax("POST","php/contenthandler.php?module=customers&command=emailGroup",{groupid:a,subject:b,bcc:c,text:d},handleEmailResult,"Emailen unm\u00f6glich",!0)});$(".vacationcollapsible").off("collapsibleexpand").on("collapsibleexpand",function(a){a=this.id.split("_");"allvacations"==a[0]&&updateVacationsOfCustomer(a[1])});
$(".billscollapsible").off("collapsibleexpand").on("collapsibleexpand",function(a){a=this.id.split("_");"allbills"==a[0]&&updateBillsOfCustomer(a[1])});$("#customerdate").off("change").on("change",function(a){startCustomerSearch()});$("#customeropenbills").off("change").on("change",function(a){startCustomerSearch()});$(".paymentpayallguests").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id.split("_")[2];doAjax("POST","php/contenthandler.php?module=customers&command=payallguests",
{paymentid:a},handlePayAllResult,"Deklaration alle G\u00e4ste als bezahlt unm\u00f6glich",!0)})}
function bindVacations(){$(".vacationentry").off("collapsibleexpand").on("collapsibleexpand",function(a){a.stopImmediatePropagation();a.preventDefault()});$(".billentry").off("collapsibleexpand").on("collapsibleexpand",function(a){a.stopImmediatePropagation();a.preventDefault()});$(".newvacationscollapsible").off("collapsibleexpand").on("collapsibleexpand",function(a){a.stopImmediatePropagation();a.preventDefault()});$(".newvacation").off("click").on("click",function(a){a.stopImmediatePropagation();
a.preventDefault();a=this.id.split("_")[1];var b=getCheckinouts("#cusfield_newcheckin_"+a,"#cusfield_newcheckout_"+a);if(b.valid){var c=$("#cusfield_vacremark_"+a).val();if(200<c.length)return cusAlertTextLength("Bemerkung"),!1;var d=$("#cusfield_cusfield_newroom_"+a).val();if(50<d.length)return cusAlertTextLength("Zimmer"),!1;doAjax("POST","php/contenthandler.php?module=customers&command=newVacation",{id:a,checkin:b.checkin,checkout:b.checkout,room:d,remark:c},handleChangeVacationResult,"Aufenthalt anlegen unm\u00f6glich",
!0)}else alert(CUS_CHECKIN_AFTER_OUT[l])});$(".delvacation").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id.split("_")[1];doAjax("POST","php/contenthandler.php?module=customers&command=delVacation",{id:a},handleChangeVacationResult,"Aufenthalt l\u00f6schen unm\u00f6glich",!0)});$(".unpaybill").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();var b=this.id.split("_")[1];$("#stornocode").val("");$("#stornoreason").val("");
areYouSureCancel(CUS_STORNO_QUEST_TITLE[l],CUS_STORNO_QUEST_TEXT[l],CUS_YES[l],function(){var c={id:b,code:$("#stornocode").val(),remark:$("#stornoreason").val()};doAjax("POST","php/contenthandler.php?module=customers&command=unpay",c,handleChangeBillResult,"Deklaration als unbezahlt unm\u00f6glich",!0)})});$(".paymentpay").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();var b=this.id.split("_");a=b[2];var c=b[3],d=b=b[4];if("all"==b){var e=[];cusbills[a].forEach(function(f,
g){e[e.length]=f.id});d=e.join(",")}doAjax("GET","php/contenthandler.php?module=bill&command=createpaidguestbill",{billids:d,paymentid:c},handleChangeBillResult,"Fehler Bezahlungvorgang",!0)});$(".printbill").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id.split("_")[1];doAjax("POST","php/contenthandler.php?module=customers&command=printbill",{id:a},null,"Drucken unm\u00f6glich",!0)});$(".printallbills").off("click").on("click",function(a){a.stopImmediatePropagation();
a.preventDefault();a=this.id.split("_")[1];doAjax("POST","php/contenthandler.php?module=customers&command=printallbills",{id:a},null,"Drucken alle unm\u00f6glich",!0)});$(".reportallbillsofsinglecus").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id.split("_")[1];window.open("php/contenthandler.php?module=customers&command=reportcustomerbills&cusid="+a,"_blank")})}
function bindGuestexportBtns(){$("#guestexport").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();window.open("php/contenthandler.php?module=customers&command=exportguests","_blank")})}function updateVacationsOfCustomer(a){doAjax("GET","php/contenthandler.php?module=customers&command=getVacations",{cusid:a},handleVacationsResult,null,!0)}
function updateBillsOfCustomer(a){doAjax("GET","php/contenthandler.php?module=customers&command=getBills",{cusid:a},handleBillsResult,null,!0)}function handleVacationsResult(a){if("OK"===a.status){var b=a.msg.vacations;a=a.msg.cusid;for(var c="",d=0;d<b.length;d++){var e=b[d];c+=renderAVacation(a,e.id,e.checkin,e.checkout,e.room,e.remark)}$("#vacationsarea_"+a).html(c);$("#vacationsarea_"+a).trigger("create");bindVacations()}}
function handleBillsResult(a){if("OK"===a.status){var b=a.msg.bills;a=a.msg.cusid;cusbills[a]=b;for(var c=!1,d="",e=!1,f=0;f<b.length;f++){var g=b[f];0==g.paid&&(c=!0);var h=!0;0==g.closed&&(h=!1);d+=renderABill(a,g.id,g.billuid,g.billdate,g.brutto,g.guestinfo,g.paid,h);0==g.closed&&(e=!0)}if(0<b.length){if(c)for(d+="<br><b>"+CUS_DECLARE_ALL_PAY[l]+"</b>:<br>",f=0;f<payments.length;f++)b=payments[f],d+=createApplyButton("payment_"+a+"_"+b.id+"_all",b.name,"e","paymentpay");e&&(d+=createApplyButton(a+
"_printallbills",CUS_PRINT_ALL[l],"f","printallbills"),d+=createApplyButton(a+"_reportallbillsofsinglecus",CUS_REPORT[l],"f","reportallbillsofsinglecus"))}$("#billsarea_"+a).html(d);$("#billsarea_"+a).trigger("create");bindVacations()}}
function renderAVacation(a,b,c,d,e,f){a=createCollapsibleStartGeneral("vacationentry_"+a,c+" - "+d,"c","vacationentry",!0);a=a+("<p>Check-in: "+c)+("<p>Check-out: "+d)+("<p>"+CUS_ROOM_LABEL[l]+": "+e);a+="<p>"+CUS_REMARK_LABEL[l]+f;a+=createDeleteButton(b+"_delvacation",CUS_DEL[l],"d","delvacation");return a+="</div>"}
function renderABill(a,b,c,d,e,f,g,h){f=e.replace(".",decpoint)+" "+currency;var k="c";1==g&&(k="f");var m="";h&&(m=" - "+CUS_CLOSED[l]+" - ");f=createCollapsibleStartGeneral("billentry_"+a,d+" - "+f+m,k,"billentry",!0);f+="<p>"+CUS_BILLID[l]+": "+c;f+="<p>"+CUS_BILLDATE[l]+": "+d;f+="<p>"+CUS_BILLBRUTTO[l]+": "+e.replace(".",decpoint);h||(f=0==g?f+createPaymentsArea(a,b,CUS_DECLAREPAY[l]):f+createApplyButton(b+"_unpaybill",CUS_DECLAREUNPAY[l],"d","unpaybill"));f+=createApplyButton(b+"_printbill",
CUS_PRINTBILL[l],"f","printbill");return f+"</div>"}function handleEmailResult(a){"OK"===a.status?alert("Aktion abgeschlossen"):alert("Error: "+a.msg)}function handleChangeVacationResult(a){"OK"===a.status?(a=a.cusid,$("#cusfield_newcheckin_"+a).val(""),$("#cusfield_newcheckout_"+a).val(""),$("#cusfield_cusfield_newroom_"+a).val(""),$("#cusfield_vacremark_"+a).val(""),updateVacationsOfCustomer(a)):alert("Error: "+a.msg)}
function handleChangeBillResult(a){"OK"===a.status?updateBillsOfCustomer(a.cusid):alert("Error: "+a.msg)}function handlePayAllResult(a){"OK"===a.status?startCustomerSearch():alert("Error: "+a.msg)}function deleteCustomerCore(a){doAjax("POST","php/contenthandler.php?module=customers&command=deleteCustomer",{id:a},handleDeleteCustomerResult,"Gast l\u00f6schen unm\u00f6glich",!0)}
function deleteGroupCore(a){doAjax("POST","php/contenthandler.php?module=customers&command=deleteGroup",{id:a},handleDeleteGroupResult,"Gruppe l\u00f6schen unm\u00f6glich",!0)}function areYouSureCus(a,b,c,d){$("#sure .sure-1").text(a);$("#sure .sure-2").text(b);$("#sure .sure-do").text(c).off("click.sure").on("click.sure",function(){d()});$(this).off("click.sure");$.mobile.changePage("#sure")}
function startSearch(){var a={search:$("#groupsearch").val().trim()};doAjax("POST","php/contenthandler.php?module=customers&command=getGroups",a,handleGetGroupsResult,"G\u00e4steabfrage unm\u00f6glich",!0)}
function startCustomerSearch(){var a=$("#customersearch").val().trim(),b=$("#customersearchremark").val().trim(),c=$("#customersearchaddress").val().trim(),d=getDate("#customerdate"),e="";null!=d&&""!=d&&(e=d.year+"-"+d.month+"-"+d.day);d=0;$("#customeropenbills").is(":checked")&&(d=1);doAjax("POST","php/contenthandler.php?module=customers&command=getCustomers",{search:a,remark:b,address:c,date:e,onlyopenbills:d},handleGetCustomerResult,"G\u00e4steabfrage unm\u00f6glich",!0)}
function clearNewCustomerFields(){$("#newcustomername").val("");$("#newcustomeremail").val("");$("#newcustomeraddress").val("");$("#newcustomerremark").val("");$("#newcustomerphone").val("");$("#newcustomermobil").val("");$("#newcustomerwww").val("");$("#newcustomerhello").val("");$("#newcustomerregards").val("");$("#newcustomercheckin").val("");$("#newcustomercheckout").val("");$("#newcustomerroom").val("");$("#newcustomerpermanent").prop("checked",!1)}
function handleCreateCustomerResult(a){if("OK"===a.status){clearNewCustomerFields();if(1==a.code){var b=CUS_ALREADY_CUS_NAME[l];b=b.replace("%number%",a.value);alert(b)}startSearch()}else alert(CUS_ACTION_FAILED[l]+": "+a.msg)}function clearNewGroupFields(){$("#newgroupname").val("");$("#newgroupremark").val("")}function handleCreateGroupResult(a){"OK"===a.status?(clearNewGroupFields(),startSearch()):1==a.code?alert(CUS_GROUP_EXISTS[l]):alert(CUS_ACTION_FAILED[l]+": "+a.msg)}
function handleChangeCustomerResult(a){"OK"===a.status?startSearch():alert(CUS_ACTION_FAILED[l]+": "+a.msg)}function handleDeleteCustomerResult(a){"OK"===a.status?startSearch():alert(CUS_ACTION_FAILED[l]+": "+a.msg)}function handleDeleteGroupResult(a){"OK"===a.status?startSearch():alert(CUS_ACTION_FAILED[l]+": "+a.msg)}function handleChangeGroupResult(a){"OK"===a.status?startSearch():alert(CUS_ACTION_FAILED[l]+": "+a.msg)}
function createInputTextField(a,b,c,d,e){a='<div class="ui-field-contain">\t<label id="label_'+(c+"_"+a+'" for="'+b+"field_"+c+"_"+a+'">'+d+':</label>\t<input id="')+(b+"field_"+c+"_"+a+'" type="text" data-mini="true" class="whiteinput" value="'+toHtml(e)+'" />');return a+"</div>"}
function createTextAreaField(a,b,c,d,e){a='<div class="ui-field-contain">\t<label id="label_'+(c+"_"+a+'" for="'+b+"field_"+c+"_"+a+'">'+d+'</label>\t<textarea cols="40" rows="8" name="')+(b+"field_"+c+"_"+a+'" id="'+b+"field_"+c+"_"+a+'" data-theme="a">')+toHtml(e);a+="</textarea>";return a+="</div>"}
function createCheckbox(a,b,c,d,e){var f="";1==e&&(f=" checked ");return a='<div class="ui-field-contain">\t<label id="label_'+(c+"_"+a+'" for="'+b+"field_"+c+"_"+a+'">'+d+'</label>\t<input type="checkbox" name="')+(b+"field_"+c+"_"+a+'" id="'+b+"field_"+c+"_"+a+'" '+f+" ></div>")}
function createDateTimePicker(a,b,c){return a='<div data-role="fieldcontain" id="datepickerarea">\t<label for="'+(a+'"><span id=datetxt>'+b+'</span>: </label>\t<input data-role="date" data-inline="true" type="text" id="')+(a+'" data-theme="'+c+'"></div>')}function createCollapsibleStartNew(a,b,c){return'<div data-role="collapsible" id="newcustomerdiv_'+a+'" data-theme="'+c+'" data-content-theme="'+c+'"><h3>'+(toHtml(b)+"</h3>")}
function createCollapsibleStartGeneral(a,b,c,d,e){var f=" ";!1===e&&(f=' style="display:none;" ');return'<div data-role="collapsible" id="'+a+'" data-theme="'+c+'" data-content-theme="'+c+'" class="'+d+'" '+f+"><h3>"+(toHtml(b)+"</h3>")}function createApplyButton(a,b,c,d){return'<button type="submit" data-theme="'+c+'" class="'+d+'" data-icon="check" id="applycustomer_'+a+'">'+b+"</button>"}
function createDeleteButton(a,b,c,d){return'<button type="submit" data-theme="'+c+'" class="'+d+'" data-icon="delete" id="deletecustomer_'+a+'">'+b+"</button>"}function createApplyDeleteButtons(a,b,c){b='<div class="ui-grid-a" class="noprint"><div class="ui-block-a">'+(createApplyButton(a,CUS_APPLY[l],"f",b)+"</div>");b+='<div class="ui-block-b">'+createDeleteButton(a,CUS_DEL[l],"d",c)+"</div>";return b+"</div>"}
function renderACustomer(a){var b=a.id,c="";null!=a.openbillsum&&""!=a.openbillsum&&(c=" ("+a.openbillsum,c=c.replace(".",decpoint)+" "+currency+")");c=createCollapsibleStartNew(b,a.name+c,"c");c=c+"<p><form>"+createInputTextField(b,"cus","name","Name",a.name);c+=createTextAreaField(b,"cus","address",CUS_ADR_LABEL[l],a.address);c+=createInputTextField(b,"cus","phone",CUS_PHONE_LABEL[l],a.phone);c+=createInputTextField(b,"cus","mobil",CUS_MOBIL_LABEL[l],a.mobil);c+=createInputTextField(b,"cus","email",
"E-Mail",a.email);c+=createInputTextField(b,"cus","www",CUS_WWW_LABEL[l],a.www);c+=createInputTextField(b,"cus","hello",CUS_HELLO_LABEL[l],a.hello);c+=createTextAreaField(b,"cus","regards",CUS_REGARDS_LABEL[l],a.regards);c+=createCheckbox(b,"cus","permanentguest",CUS_PERMANENTGUEST[l],a.permanent);c+=createTextAreaField(b,"cus","remark",CUS_REMARK_LABEL[l],a.remark);c+=createGroupList(a);c=c+"<p><i>"+(CUS_CREATED[l]+": "+a.created+"<br>");c+=CUS_LAST_MODIFIED[l]+": "+a.lastmodified;c=c+"</i>"+createApplyDeleteButtons(b,
"applycustomer","deletecustomer");c=c+"</form>"+createCollapsibleStartGeneral("allbills_"+b,CUS_BILLS[l],"e","billscollapsible",!0);c=c+('<p><div id="billsarea_'+b+'"><img src="php/3rdparty/images/ajax-loader.gif"/></div></div>')+createCollapsibleStartGeneral("allvacations_"+b,CUS_VACATIONS[l],"e","vacationcollapsible",!0);c=c+('<p><div id="vacationsarea_'+b+'"><img src="php/3rdparty/images/ajax-loader.gif"/></div>')+createCollapsibleStartGeneral("newvacations_"+b,CUS_NEWVACATIONS[l],"c","newvacationscollapsible",
!0);c+=createDateTimePicker("cusfield_newcheckin_"+b,"Check-in","a");c+=createDateTimePicker("cusfield_newcheckout_"+b,"Check-out","a");c+=createInputTextField(b,"cus","cusfield_newroom",CUS_ROOM_LABEL[l],"");c+=createInputTextField(b,"cus","vacremark",CUS_REMARK_LABEL[l],"");c+=createApplyButton(b+"_newvacation",CUS_APPLY[l],"f","newvacation");c+="</div></div>";return c+="</div>"}
function renderCustomers(a){for(var b="",c=0;c<a.length;c++)b+=renderACustomer(a[c]);$("#customersearchresult").html(b);$("#customersearchresult").trigger("create");for(c=0;c<a.length;c++)customizeDatePicker("#cusfield_newcheckin_"+a[c].id,""),customizeDatePicker("#cusfield_newcheckout_"+a[c].id,"")}function handleGetCustomerResult(a){"OK"===a.status?(customers=a.msg,renderCustomers(a.msg),bindOnDynamicCustomersBtn()):alert(CUS_ACTION_FAILED[l]+": "+a.msg)}
function handleGetGroupsResult(a){"OK"===a.status?(renderGroups(a.msg.filtered),allgroups=a.msg.all,startCustomerSearch(),createAssignSelListOfGroupsInCustomerArea(),doVisibilityOfAssignmentFields()):alert(CUS_ACTION_FAILED[l]+": "+a.msg)}
function renderAGroup(a){var b=a.id,c=createCollapsibleStartNew(b,a.name,"c");c=c+"<p><form>"+createInputTextField(b,"grp","name","Name",a.name);c+=createTextAreaField(b,"grp","remark",CUS_REMARK_LABEL[l],a.remark);var d=a.customers;if(0<d.length){c=c+"<p><div class='customerlistbox'>"+(CUS_CONTAINED_IN_GRP[l]+":<br>");for(var e=0;e<d.length;e++)c+="- "+d[e].name+"<br>";c+="</div>"}c=c+"<p><i>"+(CUS_CREATED[l]+": "+a.created+"<br>");c=c+"</i>"+createApplyDeleteButtons(b,"applygroup","deletegroup");
c+=createCollapsibleStartGeneral("groupemail_"+b,"Email","e","groupemailentry",!0);c+=createInputTextField(b,"grpemailsubject","grpemailsubject","Subject","");c+=createInputTextField(b,"grpemailbcc","grpemailbcc","BCC","");c+=createTextAreaField(b,"grpemailtext","grpemailtext","Text","");c+="<p>"+CUS_PLACEHOLDER_HINT[l]+" <i>"+CUS_EMAIL_WARNING[l]+"</i>";c+="<p>"+createApplyButton(b+"_groupsendemail",CUS_SEND_EMAIL[l],"f","groupsendemail");return c+"</div></form></div>"}
function renderGroups(a){for(var b="",c=0;c<a.length;c++)b+=renderAGroup(a[c]);$("#groupsearchresult").html(b);$("#groupsearchresult").trigger("create")}function isCustomerInGroup(a,b){for(var c=0;c<a.length;c++)if(a[c].groupid==b)return!0;return!1}
function createGroupList(a){var b=a.id;a=a.groups;var c='<ul  data-role="listview" id="grouplist_'+b+'" data-divider-theme="a" data-inset="true"><li data-role="list-divider" data-theme="b" data-role="heading">'+(CUS_GRP_ASS_LIST[l]+"</li>");for(var d=0;d<allgroups.length;d++){var e=allgroups[d],f=e.id,g="c",h="delete",k="notingroup";isCustomerInGroup(a,f)&&(g="f",h="check",k="ingroup");c+='<li id="grplistitem_'+b+"_"+f+'" data-theme="'+g+'" data-icon="'+h+'" class="'+k+'"><a href="#" id="grpass_'+
b+"_"+f+'" class="grpsel">'+toHtml(e.name)+"</a></li>"}return c+"</ul>"}function cusAlertTextLength(a){alert(CUS_ALERT_TEXT_LEN[l]+a)}
function cusCheckTextLengths(a){return 50<a.name.length?(cusAlertTextLength("Name"),!1):200<a.addr.length?(cusAlertTextLength(CUS_ADR_LABEL[l]),!1):30<a.phone.length?(cusAlertTextLength(CUS_PHONE_LABEL[l]),!1):30<a.mobil.length?(cusAlertTextLength(CUS_MOBIL_LABEL[l]),!1):50<a.email.length?(cusAlertTextLength("Email"),!1):50<a.www.length?(cusAlertTextLength(CUS_WWW_LABEL[l]),!1):500<a.remark.length?(cusAlertTextLength(CUS_REMARK_LABEL[l]),!1):!0}
function customizeDatePicker(a,b){var c="de";1==l?c="en":2==l&&(c="es");var d=(new Date).getFullYear();d=d-10+":"+(d+3);$(a).datepicker($.datepicker.regional[c]).datepicker("option",{changeMonth:!0,changeYear:!0,yearRange:d});null!=b&&""!=b?$(a).datepicker("setDate",new Date(b)):$(a).val("")}
function getDate(a){var b=$(a).val();if(void 0==b||""==b.trim())return null;a=$(a).datepicker("getDate");return{day:("0"+a.getDate()).slice(-2),month:("0"+(a.getMonth()+1)).slice(-2),year:a.getFullYear(),date:a}}function getCheckinouts(a,b){a=getDate(a);b=getDate(b);var c="";null!=a&&""!=a&&(c=a.year+"-"+a.month+"-"+a.day);var d="";null!=b&&""!=b&&(d=b.year+"-"+b.month+"-"+b.day);var e=!0;null!=a&&""!=a&&null!=b&&""!=b&&a.date>b.date&&(e=!1);return{checkin:c,checkout:d,valid:e}}
function areYouSureCancel(a,b,c,d){$("#cancelsure .sure-1").text(a);$("#cancelsure .sure-2").text(b);$("#cancelsure .sure-do").text(c).off("click.cancelsure").on("click.cancelsure",function(e){e.stopImmediatePropagation();e.preventDefault();$("#nocancelbtn").off("click");$("#cancelsure").dialog("close");$.mobile.changePage("#info-page");d();$(this).off("click.cancelsure")});$("#nocancelbtn").off("click").on("click",function(e){e.stopImmediatePropagation();e.preventDefault();$("#cancelsure .sure-do").text(c).off("click.cancelsure");
$("#cancelsure").dialog("close");$.mobile.changePage("#info-page")});$.mobile.changePage("#cancelsure");setTimeout(function(){$("#stornocode").val("");$("#stornoreason").val("")},1E3)}
function createAssignSelListOfGroupsInCustomerArea(){var a="";0>selGroupForAssigment&&(a+="<input id='newgrpforassignment' type='text' value='' data-mini='true' placeholder='Neue Gruppe' class='whiteinput' />");a+='<select name="grpAssignmentSelection" id="grpAssignmentSelection" data-theme="e">';a+="<option value='-1'>-</option>";allgroups.forEach(function(b){var c="";b.id==selGroupForAssigment&&(c=" selected ");a+="<option value='"+b.id+"' "+c+">"+toHtml(b.name)+"</option>"});a+="</select>";$("#grpassdiv").html(a);
$("#grpassdiv").trigger("create");bindGrpAssignmentForFilteredList()}function bindGrpAssignmentForFilteredList(){$("#grpAssignmentSelection").off("change").on("change",function(a){a.stopImmediatePropagation();a.preventDefault();selGroupForAssigment=parseInt($("#grpAssignmentSelection").val());doVisibilityOfAssignmentFields();createAssignSelListOfGroupsInCustomerArea()})}
function doVisibilityOfAssignmentFields(){0>selGroupForAssigment?($("#newgrpforassignment").show(),$("#newgrpforassbtn").show(),$("#existentgrpforassbtn").hide(),$("#removefromgroupbtn").hide()):($("#newgrpforassignment").hide(),$("#newgrpforassbtn").hide(),$("#existentgrpforassbtn").show(),$("#removefromgroupbtn").show());bindGrpButtonsAssignmentForFilteredList()}function getIdListOfFilteredCustomers(){var a=[];customers.forEach(function(b){a[a.length]=b.id});return a}
function bindGrpButtonsAssignmentForFilteredList(){$("#existentgrpforassbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a={customers:getIdListOfFilteredCustomers(),groupid:selGroupForAssigment};doAjax("POST","php/contenthandler.php?module=customers&command=assigncustomerstogroup",a,handleCustomerAssignments,"Fehler Zuweisung")});$("#newgrpforassbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a={customers:getIdListOfFilteredCustomers(),
groupname:$("#newgrpforassignment").val()};doAjax("POST","php/contenthandler.php?module=customers&command=assigncustomerstonewgroup",a,handleCustomerAssignments,"Fehler Zuweisung zu neuer Gruppe")});$("#removefromgroupbtn").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a={customers:getIdListOfFilteredCustomers(),groupid:selGroupForAssigment};doAjax("POST","php/contenthandler.php?module=customers&command=removefromgroup",a,handleCustomerAssignments,"Fehler Austragung")})}
function handleCustomerAssignments(a){"OK"!=a.status?alert("Fehler: "+a.msg):doAjax("POST","php/contenthandler.php?module=customers&command=getGroups",{search:""},handleGetGroupsResult,"G\u00e4steabfrage unm\u00f6glich",!0)};
