function User(){var f=this;this.createCollapsibeOfUser=function(a,b,g,h,e,l,k,p,m,n,r){d=new Date;var c='<div data-role="collapsible" id="userdef_'+b+'"';c=m?c+' data-theme="d" data-content-theme="d">':c+' data-theme="c" data-content-theme="c"><p /><img src="php/contenthandler.php?module=admin&command=getuserphotoinsession&userid='+(a+"&d="+d.getTime()+'" style="width:100px;" />');var q="";0<r&&(q="<div class='userup' id=userup_"+a+">&uarr;</div>");c+="<h3>"+g+q+"</h3><form>";m?(c+=createLabelWithTextField("userlabel_username_new",
MAN_USER_NAME[lang],MAN_USER_NAME[lang]),c+=createLabelWithTextField("userlabel_fullname_new",MAN_USER_FULLNAME[lang],MAN_USER_FULLNAME[lang]),c+=createLabelWithTextField("userlabel_password_new",MAN_USER_PASS[lang],MAN_USER_PASS[lang]),c+=createLabelWithTextField("userlabel_articletag_new",MAN_USER_ARTICLETAG[lang],MAN_USER_ARTICLETAG[lang]),c+=f.createCheckbox("userlabel_isowner_new",MAN_OWNER[lang],0,"d")):(c+=createLabelWithTextFieldWithContent("userlabel_username_"+b,MAN_USER_NAME[lang],MAN_USER_NAME[lang],
g),c+=createLabelWithTextFieldWithContent("userlabel_fullname_"+b,MAN_USER_FULLNAME[lang],MAN_USER_FULLNAME[lang],h),c+=createLabelWithTextFieldWithContent("userlabel_articletag_"+b,MAN_USER_ARTICLETAG[lang],MAN_USER_ARTICLETAG[lang],p),c+=f.createCheckbox("userlabel_isowner_"+b,MAN_OWNER[lang],parseInt(e),"c"));a=createRolesArr(n);c+=createLabelWithOption("userlabel_",b,"userrole",MAN_ROLE[lang],a,l);c+=createLabelWithOption("userlabel_",b,"userarea",MAN_AREA[lang],createTableAreaValueArr(),k);m?
c+='<button data-theme="f" data-icon="plus" id="CreateNewUser">'+MAN_CREATE[lang]+"</button>":(c+='<button data-theme="f" data-icon="check" class="userUpdateButton" id="userupdatebtn_'+b+'">'+MAN_CHANGE_ROLE_AREA[lang]+"</button>",c+=createButtonWithTextField("changepasswordbtn_"+b,"Passwort \u00e4ndern","Anderes Passwort"),c+='<button data-theme="d" data-icon="minus" class="userDeleteButton" id="deleteuserbtn_'+b+'">L\u00f6schen</button>');return c+"</form></div>"};this.fillUserListIntoGui=function(a){var b=
"",g=a.roles,h=!1;a.users.forEach(function(e,l){var k=e.id,p=e.username,m=e.fullname,n=e.isowner;1==n&&(h=!0);b+=f.createCollapsibeOfUser(k,"userid_"+k,p,m,n,e.roleid,e.tablearea,e.articletag,!1,g,l)});b+=f.createCollapsibeOfUser(null,"userid_newuser_newuser",MAN_NEW_USER[lang],"",0,0,0,"",!0,g,-1);$("#userlist").html(b);$("#userpart").trigger("create");h||alert("Mindestens ein Benutzer sollte als Arbeitgeber (Inhaber) deklariert werden, damit Trinkgelder f\u00fcr den Arbeitgeber steuerlich korrekt verbucht werden.");
f.dynamicUserBinding()};this.askAndFillUserList=function(){doAjax("GET","php/contenthandler.php?module=admin&command=getUserList",null,f.fillUserListIntoGui,"no user data received",!0)};this.askAndFillUserListNoData=function(a){"noadmin"===a?alert(MAN_NO_ADMIN[lang]):f.askAndFillUserList()};this.handleDelUser=function(a){"OK"!==a.status?alert("Fehler: "+a.msg):setTimeout(function(){document.location.href="manager.html?v={VERSION}"},250)};this.doCreateNewUser=function(a){"OK"===a.status?f.askAndFillUserList():
alert("Fehler: "+a.msg)};this.dynamicUserBinding=function(){$("#CreateNewUser").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=$("#userlabel_username_new").val();var b=$("#userlabel_fullname_new").val(),g=$("#userlabel_password_new").val(),h=$("#userlabel_userrole_userid_newuser_newuser").val(),e=$("#userlabel_userarea_userid_newuser_newuser").val(),l=$("#userlabel_articletag_new").val(),k=0;$("#userlabel_isowner_new").is(":checked")&&(k=1);a={name:a.trim(),
fullname:b.trim(),isowner:k,password:g,roleid:h,area:e,articletag:l};0===a.name.length||0===a.password.length?alert("Benutzername oder Passwort sind nicht gesetzt"):doAjax("POST","php/contenthandler.php?module=admin&command=createNewUser",a,f.doCreateNewUser,"Anlegen neuer Benutzer")});$(".userUpdateButton").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id.split("_")[2];var b=$("#userlabel_username_userid_"+a).val(),g=$("#userlabel_fullname_userid_"+a).val(),
h=$("#userlabel_userrole_userid_"+a).val(),e=$("#userlabel_userarea_userid_"+a).val(),l=$("#userlabel_articletag_userid_"+a).val(),k=0;$("#userlabel_isowner_userid_"+a).is(":checked")&&(k=1);a={userid:a,username:b.trim(),fullname:g.trim(),isowner:k,roleid:h,area:e,articletag:l};doAjax("POST","php/contenthandler.php?module=admin&command=updateUser",a,f.askAndFillUserListNoData,"Benutzerdaten")});$(".userDeleteButton").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();
a={userid:this.id.split("_")[2]};doAjax("POST","php/contenthandler.php?module=admin&command=deleteUser",a,f.handleDelUser,"Benutzer entfernen")});$(".changepassword").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a=this.id.split("_")[3];var b=$("#userpassword_changepasswordbtn_userid_"+a).val();0===b.length?alert("Passwort ist leer!"):doAjax("POST","php/contenthandler.php?module=admin&command=changepassword",{userid:a,password:b},f.askAndFillUserListNoData,"Neues Passwort")});
$(".userup").off("click").on("click",function(a){a.stopImmediatePropagation();a.preventDefault();a={userid:this.id.split("_")[1]};doAjax("POST","php/contenthandler.php?module=admin&command=userup",a,f.askAndFillUserListNoData,"Neues Passwort")})};this.createCheckbox=function(a,b,g,h){var e="";1===g&&(e=" checked");return a='<fieldset data-role="controlgroup"><input type="checkbox" name="'+(a+'" id="'+a+'" data-theme="'+h+'" '+e+' /><label for="')+(a+'">'+b+"</label></fieldset>")}};
